using System;
using System.Collections.Generic;
using System.Linq;
using StarterAssets;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public static class GuardianMistiProjectValidator
{
    private static readonly List<string> Errors=new();
    private static readonly string[] Scenes={"Assets/Scenes/MainMenu.unity","Assets/Scenes/Level01.unity","Assets/Scenes/Level02.unity","Assets/Scenes/Level03.unity"};
    private static readonly string[] Prefabs={"Assets/Prefabs/Player/GameplayPlayer.prefab","Assets/Prefabs/UI/GameplayHUD.prefab","Assets/Prefabs/Systems/GameplaySystems.prefab","Assets/Prefabs/Gameplay/FacilityExitDoor.prefab","Assets/Prefabs/Gameplay/InteriorProtectionZone.prefab","Assets/Prefabs/Gameplay/CollectibleItem.prefab","Assets/Prefabs/Gameplay/LevelExit.prefab","Assets/Prefabs/Gameplay/SafeZone.prefab","Assets/Prefabs/Gameplay/EvacuationTerminal.prefab","Assets/Prefabs/Gameplay/EmergencyBeacon.prefab","Assets/Prefabs/Gameplay/EmergencyBackpack.prefab","Assets/Prefabs/Gameplay/EmergencyRadio.prefab","Assets/Prefabs/Gameplay/AccessKey.prefab","Assets/Prefabs/Environment/FacilityModule.prefab","Assets/Prefabs/Environment/KenneyDesk.prefab","Assets/Prefabs/Environment/KenneyChair.prefab","Assets/Prefabs/Environment/KenneyShelf.prefab","Assets/Prefabs/Environment/KenneyDoorFrame.prefab","Assets/Prefabs/Environment/KenneyRock.prefab","Assets/Prefabs/Environment/KenneySignpost.prefab","Assets/Prefabs/Environment/KenneyRescueTent.prefab","Assets/Prefabs/Environment/Desk.prefab","Assets/Prefabs/Environment/Chair.prefab","Assets/Prefabs/Environment/Shelf.prefab","Assets/Prefabs/Environment/EmergencySign.prefab"};
    [MenuItem("Guardian Misti/Validate Project")]
    public static void ValidateProject()
    {
        Errors.Clear();Time.timeScale=1f;
        foreach(string p in Scenes.Concat(Prefabs))NeedAsset(p);
        foreach(string p in new[]{"Assets/ScriptableObjects/Items/EmergencyBackpack.asset","Assets/ScriptableObjects/Items/EmergencyRadio.asset","Assets/ScriptableObjects/Items/AccessKey.asset","Assets/Settings/GuardianMisti/MainMenuVolume.asset","Assets/Settings/GuardianMisti/Level01Volume.asset","Assets/Settings/GuardianMisti/Level02Volume.asset"})NeedAsset(p);
        foreach(string p in new[]{"Assets/ThirdParty/Kenney/FurnitureKit/Models/desk.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/chairDesk.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/bookcaseOpen.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/doorway.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/rock-a.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/signpost.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/tent-canvas.fbx","Assets/ThirdParty/ATTRIBUTION.md","Artifacts/ExternalAssetManifest.json"})NeedAsset(p);
        var enabled=EditorBuildSettings.scenes.Where(s=>s.enabled).Select(s=>s.path).ToArray();if(!enabled.SequenceEqual(Scenes))Error("Build scenes must be MainMenu, Level01, Level02, Level03 and in order.");
        ValidateItem("EmergencyBackpack",GameIds.EmergencyBackpack);ValidateItem("EmergencyRadio",GameIds.EmergencyRadio);ValidateItem("AccessKey",GameIds.AccessKey);
        ValidateScene(Scenes[0],false,false);ValidateScene(Scenes[1],true,false);ValidateScene(Scenes[2],true,true);foreach(string assetHubError in GuardianMistiAssetHubValidator.Validate())Error(assetHubError);
        if(Errors.Count>0){foreach(string e in Errors)Debug.LogError("VALIDATION: "+e);throw new Exception($"Guardian Misti validation failed with {Errors.Count} actionable error(s).");}
        Debug.Log("GUARDIAN_MISTI_VALIDATION_SUCCESS");
    }
    private static void ValidateScene(string path,bool gameplay,bool final)
    {
        if(!System.IO.File.Exists(path))return;var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var roots=scene.GetRootGameObjects();var all=roots.SelectMany(r=>r.GetComponentsInChildren<Transform>(true)).Select(t=>t.gameObject).ToArray();
        if(roots.Count(r=>r.name=="Generated_GuardianMisti")!=1)Error(path+": exactly one Generated_GuardianMisti root is required.");
        Exactly<EventSystem>(all,path);Exactly<AudioListener>(all,path);Need<Canvas>(all,path);Need<SceneLoader>(all,path);
        var es=all.SelectMany(g=>g.GetComponents<InputSystemUIInputModule>()).ToArray();if(es.Length!=1)Error(path+": EventSystem must use exactly one InputSystemUIInputModule.");
        foreach(var go in all){if(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(go)>0)Error(path+": Missing Script on "+go.name);foreach(var r in go.GetComponents<Renderer>()){if(r.sharedMaterials.Any(m=>m==null))Error(path+": renderer has missing material on "+go.name);foreach(var m in r.sharedMaterials)if(m!=null&&(m.shader==null||m.shader.name.Contains("Error")))Error(path+": invalid/pink shader on "+go.name);}}
        ValidateSameSceneReferences(scene,all);
        var scaler=all.SelectMany(g=>g.GetComponents<CanvasScaler>()).FirstOrDefault();if(scaler==null||scaler.uiScaleMode!=CanvasScaler.ScaleMode.ScaleWithScreenSize)Error(path+": CanvasScaler must use Scale With Screen Size.");
        var sessions=all.SelectMany(g=>g.GetComponents<SimulationSession>()).ToArray();if(!gameplay&&sessions.Length>0)Error(path+": MainMenu must not contain SimulationSession.");if(gameplay&&final&&sessions.Length>0)Error(path+": Level02 must receive the persistent session from Level01, not define another one.");if(gameplay&&!final){if(sessions.Length!=1)Error(path+": Level01 requires exactly one SimulationSession.");else{if(sessions[0].transform.parent!=null)Error(path+": SimulationSession must be a scene-root object.");var sessionSo=new SerializedObject(sessions[0]);var iterator=sessionSo.GetIterator();while(iterator.NextVisible(true))if(iterator.propertyType==SerializedPropertyType.ObjectReference&&iterator.objectReferenceValue is Component component&&component.gameObject.scene==scene)Error(path+": SimulationSession must not serialize scene-local references.");}}
        var recorders=all.SelectMany(g=>g.GetComponents<SimulationResearchRecorder>()).ToArray();if(!gameplay&&recorders.Length>0)Error(path+": MainMenu must not contain a research recorder.");if(gameplay&&!final){if(recorders.Length!=1)Error(path+": Level01 requires exactly one SimulationResearchRecorder.");else if(recorders[0].transform!=sessions.SingleOrDefault()?.transform)Error(path+": research recorder must share the persistent root session object.");}if(gameplay&&final&&recorders.Length>0)Error(path+": Level02 must not define a duplicate research recorder.");if(SimulationSession.BestTimeKey!="GuardianMisti.BestTimeSeconds")Error(path+": best-time key changed unexpectedly.");if(SimulationResearchRecorder.DirectoryName!="GuardianMistiResearch"||SimulationResearchRecorder.DirectoryName.IndexOfAny(System.IO.Path.GetInvalidPathChars())>=0)Error(path+": research export directory is invalid.");
        if(!gameplay){Need<MainMenuController>(all,path);RequireText(all,"Ctrl izquierdo: Agacharse",path);RequireText(all,"GUARDIAN MISTI",path);RequireText(all,"INICIAR SIMULACIÓN",path);RequireText(all,"INSTRUCCIONES",path);RequireText(all,"SALIR",path);ValidateButtons(all,path,new[]{"PlayButton","InstructionsButton","ExitButton"});return;}
        Exactly<PlayerInput>(all,path);Exactly<StarterAssetsInputs>(all,path);Exactly<FirstPersonController>(all,path);Exactly<PlayerCrouchController>(all,path);Exactly<PlayerLookController>(all,path);Exactly<GameplayStateController>(all,path);Exactly<InteractionSystem>(all,path);Exactly<InteractionUIController>(all,path);Need<ObjectivesManager>(all,path);Need<InventoryManager>(all,path);Need<PauseController>(all,path);Need<GameplayCursorController>(all,path);Exactly<GameplayDiagnostics>(all,path);Exactly<GameplayDiagnosticsOverlay>(all,path);Exactly<GameplayRuntimeLogger>(all,path);Exactly<SimulationMetricsProbe>(all,path);Exactly<Camera>(all,path);
        var player=all.FirstOrDefault(g=>g.name=="GameplayPlayer");if(player==null||!player.CompareTag("Player"))Error(path+": GameplayPlayer missing or not tagged Player.");else ValidatePlayer(player,path);
        if(player!=null)ValidateLookController(player,path);if(all.Count(g=>g.CompareTag("MainCamera")&&g.activeInHierarchy)!=1)Error(path+": expected exactly one active MainCamera tag.");var input=all.SelectMany(g=>g.GetComponents<PlayerInput>()).SingleOrDefault();if(input==null||input.actions==null||input.defaultActionMap!="Player")Error(path+": PlayerInput actions/default Player map are not configured.");
        var interaction=all.SelectMany(g=>g.GetComponents<InteractionSystem>()).SingleOrDefault();RequireRef(interaction,"playerCamera",path);RequireRef(interaction,"interactionUIController",path);
        var ui=all.SelectMany(g=>g.GetComponents<InteractionUIController>()).SingleOrDefault();RequireRef(ui,"promptUI",path);RequireRef(ui,"crosshairUI",path);
        var state=all.SelectMany(g=>g.GetComponents<GameplayStateController>()).SingleOrDefault();foreach(string f in new[]{"playerInput","movement","starterInputs","interaction","pausePanel","completionPanel"})RequireRef(state,f,path);var diagnostics=all.SelectMany(g=>g.GetComponents<GameplayDiagnostics>()).SingleOrDefault();foreach(string f in new[]{"stateController","playerInput","inputs","movement","characterController","interaction","pausePanel","completionPanel","runtimeLogger"})RequireRef(diagnostics,f,path);var overlay=all.SelectMany(g=>g.GetComponents<GameplayDiagnosticsOverlay>()).SingleOrDefault();foreach(string f in new[]{"diagnostics","panel","diagnosticText"})RequireRef(overlay,f,path);ValidateUi(all,path);
        if(!final){var earthquakes=all.SelectMany(g=>g.GetComponents<EarthquakeController>()).ToArray();if(earthquakes.Length!=1)Error(path+": Level01 requires exactly one EarthquakeController.");else{var quake=earthquakes[0];foreach(string f in new[]{"profile","cameraEffectRoot","dust","objectivesManager","notificationUI"})RequireRef(quake,f,path);var quakeUi=all.SelectMany(g=>g.GetComponents<EarthquakeUIController>()).SingleOrDefault();if(quakeUi==null)Error(path+": EarthquakeUIController missing.");else{foreach(string f in new[]{"earthquakeController","countdownText","intensityText"})RequireRef(quakeUi,f,path);var uiSo=new SerializedObject(quakeUi);var countdown=uiSo.FindProperty("countdownText")?.objectReferenceValue as TMPro.TMP_Text;if(countdown!=null&&(!string.IsNullOrEmpty(countdown.text)||countdown.gameObject.activeSelf))Error(path+": countdown must be authored empty and hidden; runtime state owns it.");}var dustProperty=new SerializedObject(quake).FindProperty("dust");var dust=dustProperty?.objectReferenceValue as ParticleSystem;if(dust!=null){var renderer=dust.GetComponent<ParticleSystemRenderer>();if(renderer==null||renderer.sharedMaterial==null||renderer.sharedMaterial.shader==null||renderer.sharedMaterial.shader.name.Contains("Error"))Error(path+": earthquake dust requires a valid URP particle material.");if(dust.emission.rateOverTime.constantMax>7.01f||dust.main.maxParticles>60)Error(path+": earthquake dust emission is excessive.");foreach(var t in dust.GetComponentsInChildren<Transform>(true))if(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject)>0)Error(path+": Missing Script in earthquake dust hierarchy.");}ValidateEarthquakePresentation(quake,all,path);}}
        if(all.Count(g=>g.name=="GlobalVolume")!=1||all.SelectMany(g=>g.GetComponents<Volume>()).All(v=>!v.isGlobal||v.sharedProfile==null))Error(path+": configured project-owned Global Volume required.");
        if(all.SelectMany(g=>g.GetComponents<Light>()).Count()<2)Error(path+": directional plus local guidance lighting required.");
        foreach(var i in all.SelectMany(g=>g.GetComponents<MonoBehaviour>()).Where(m=>m is IInteractable)){if(i.GetComponent<Collider>()==null)Error(path+": interactable without collider: "+i.name);}
        var ids=all.SelectMany(g=>g.GetComponents<ObjectivesManager>()).First().Objectives.Select(o=>o.Id).ToArray();var expected=final?new[]{GameIds.Level02CollectRadio,GameIds.Level02CollectAccessKey,GameIds.Level02ActivateBeacon,GameIds.Level02ReachSafeZone}:new[]{GameIds.Level01Preparation,GameIds.Level01Protect,GameIds.Level01ExitRoom,GameIds.Level01CollectBackpack,GameIds.Level01ActivateEvacuation,GameIds.Level01ReachExit};if(!ids.SequenceEqual(expected))Error(path+": objective IDs/order do not match required flow.");
        ValidateButtons(all,path,new[]{"ResumeButton","RestartButton","MenuButton"});RequireText(all,"SIMULACIÓN EN PAUSA",path);
        if(final){Need<EmergencyBeaconController>(all,path);var zone=all.SelectMany(g=>g.GetComponents<SafeZoneController>()).SingleOrDefault();if(zone==null||zone.GetComponent<Collider>()==null||!zone.GetComponent<Collider>().isTrigger)Error(path+": one-shot SafeZone trigger missing.");ValidateButtons(all,path,new[]{"ExitButton"});RequireText(all,"MISIÓN COMPLETADA",path);}else{var exit=all.SelectMany(g=>g.GetComponents<LevelExitController>()).SingleOrDefault();if(exit==null||exit.GetComponent<Collider>()==null||!exit.GetComponent<Collider>().isTrigger)Error(path+": LevelExit trigger missing.");}
        foreach(string visual in final?new[]{"EmergencyRadio","AccessKey","EmergencyBeacon","RescuePlatform","VolcanicRock","KenneyRockLandmark","KenneyEvacuationSign","KenneyRescueTent"}:new[]{"InitialDoor","EmergencyBackpack","EvacuationTerminal","EmergencySupplyCrate","EmergencyLight","KenneyEmergencyDesk","KenneyOfficeChair","KenneySupplyShelf","KenneyDoorwayDetail"})if(!all.Any(g=>g.name==visual))Error(path+": composed visual missing: "+visual);if(!final)ValidateLevel01Environment(all,path);else ValidateAftershock(all,path);ValidateVisualAssetUsage(all,path,final);
    }
    private static void ValidateAftershock(GameObject[] all,string path){var aftershocks=all.SelectMany(g=>g.GetComponents<AftershockController>()).ToArray();if(aftershocks.Length!=1){Error(path+": exactly one Level02 aftershock controller is required.");return;}var a=aftershocks[0];foreach(string f in new[]{"profile","player","stableFloor","cameraEffectRoot","warningText","dust"})RequireRef(a,f,path);if(a.GetComponent<ObjectivesManager>()==null)Error(path+": aftershock must coexist with, not replace, Level02 objectives.");var zones=all.SelectMany(g=>g.GetComponents<AftershockRiskZone>()).ToArray();if(zones.Length<1)Error(path+": marked aftershock risk zones missing.");if(zones.Any(z=>!z.GetComponent<BoxCollider>().isTrigger))Error(path+": aftershock risk zones must be triggers.");if(all.Count(g=>g.name=="ControlledAftershockRock")>5)Error(path+": aftershock dynamic prop limit exceeded.");if(!all.Any(g=>g.name=="RiskZoneMarker")||!all.SelectMany(g=>g.GetComponentsInChildren<TMPro.TMP_Text>(true)).Any(t=>t.text.Contains("RIESGO")))Error(path+": risk zones require visible Spanish signage.");}
    private static void ValidateVisualAssetUsage(GameObject[] all,string path,bool final){var required=final?new[]{("EmergencyRadio","Assets/Prefabs/Gameplay/EmergencyRadio.prefab",6),("AccessKey","Assets/Prefabs/Gameplay/AccessKey.prefab",5),("EmergencyBeacon","Assets/Prefabs/Gameplay/EmergencyBeacon.prefab",8),("SafeZone","Assets/Prefabs/Gameplay/SafeZone.prefab",10),("KenneyEvacuationSign","Assets/Prefabs/Environment/EmergencySign.prefab",3),("KenneyRescueTent","Assets/Prefabs/Environment/KenneyRescueTent.prefab",1)}:new[]{("InitialDoor","Assets/Prefabs/Gameplay/FacilityExitDoor.prefab",7),("EmergencyBackpack","Assets/Prefabs/Gameplay/EmergencyBackpack.prefab",8),("EvacuationTerminal","Assets/Prefabs/Gameplay/EvacuationTerminal.prefab",7),("KenneyEmergencyDesk","Assets/Prefabs/Environment/Desk.prefab",1),("KenneyOfficeChair","Assets/Prefabs/Environment/Chair.prefab",1),("KenneySupplyShelf","Assets/Prefabs/Environment/Shelf.prefab",1)};foreach(var spec in required){var go=all.FirstOrDefault(g=>g.name==spec.Item1);if(go==null)continue;var source=PrefabUtility.GetCorrespondingObjectFromSource(go);var sourcePath=source==null?string.Empty:AssetDatabase.GetAssetPath(source);if(sourcePath!=spec.Item2)Error(path+": selected visual is not a retained prefab instance: "+spec.Item1+" expected "+spec.Item2+" got "+sourcePath);var renderers=go.GetComponentsInChildren<Renderer>(true);if(renderers.Length<spec.Item3)Error(path+": major visual lacks recognizable multi-part geometry: "+spec.Item1);if(renderers.Any(r=>r.sharedMaterials.Length==0||r.sharedMaterials.Any(m=>m==null||m.shader==null||m.shader.name.Contains("Error"))))Error(path+": missing or error material in "+spec.Item1);var scale=go.transform.lossyScale;if(scale.x<.05f||scale.y<.05f||scale.z<.05f||scale.x>5f||scale.y>5f||scale.z>5f)Error(path+": unreasonable wrapper scale on "+spec.Item1);}if(!System.IO.File.Exists("Assets/ThirdParty/ATTRIBUTION.md")||!System.IO.File.Exists("Artifacts/ExternalAssetManifest.json"))Error(path+": third-party attribution or manifest missing.");}
    private static void ValidateEarthquakePresentation(EarthquakeController quake,GameObject[] all,string path){var so=new SerializedObject(quake);var profile=so.FindProperty("profile").objectReferenceValue as EarthquakeProfile;if(profile==null)return;foreach(string field in new[]{"<IntensityCurve>k__BackingField","<CameraShakeCurve>k__BackingField","<AudioVolumeCurve>k__BackingField","<LightFlickerCurve>k__BackingField","<DustEmissionCurve>k__BackingField","<PropForceCurve>k__BackingField"})if(new SerializedObject(profile).FindProperty(field)?.animationCurveValue==null)Error(path+": earthquake profile curve missing: "+field);if(profile.MaximumActivePhysicsProps<1||profile.MaximumActivePhysicsProps>8)Error(path+": earthquake physics prop limit must be 1..8.");if(profile.LightFlickerIntensity>.35f)Error(path+": unsafe earthquake light flicker threshold.");var cameraRoot=so.FindProperty("cameraEffectRoot").objectReferenceValue as Transform;var player=all.FirstOrDefault(g=>g.CompareTag("Player"));if(cameraRoot==null||cameraRoot==player?.transform)Error(path+": camera shake must target a presentation child, never the player transform.");foreach(string field in new[]{"debris"})RequireRef(quake,field,path);var particles=new[]{so.FindProperty("dust").objectReferenceValue as ParticleSystem,so.FindProperty("debris").objectReferenceValue as ParticleSystem};foreach(var ps in particles.Where(p=>p!=null)){var renderer=ps.GetComponent<ParticleSystemRenderer>();if(renderer.sharedMaterial==null||renderer.sharedMaterial.shader==null||renderer.sharedMaterial.shader.name.Contains("Error"))Error(path+": earthquake particle material is not URP-compatible.");}var props=all.SelectMany(g=>g.GetComponents<EarthquakeReactiveProp>()).ToArray();if(props.Length==0||props.Length>profile.MaximumActivePhysicsProps)Error(path+": reactive earthquake prop count exceeds profile limit or is zero.");foreach(var prop in props){if(!prop.RouteSafe)Error(path+": reactive prop is not marked route-safe: "+prop.name);if(prop.GetComponent<Collider>() is MeshCollider)Error(path+": dynamic earthquake prop may not use MeshCollider: "+prop.name);if(Mathf.Abs(prop.transform.position.x)<3.5f)Error(path+": reactive prop intrudes into mandatory center route: "+prop.name);}var audioClips=AssetDatabase.FindAssets("t:AudioClip");if(audioClips.Length>0){foreach(string field in new[]{"rumbleSource","alarmSource","impactSource"}){var source=so.FindProperty(field).objectReferenceValue as AudioSource;if(source==null||source.clip==null)Error(path+": available audio clips exist but earthquake source is unassigned: "+field);}}}
    private static void ValidateLevel01Environment(GameObject[] all,string path)
    {
        foreach(string required in new[]{"Level01FacilityInterior","RoomFloor","RoomCeiling","RoomBackWall","RoomLeftWall","RoomRightWall","Generated_InteriorProtectionZone","Generated_ProtectionDesk","Generated_ProtectionSign","Generated_ProtectionInstruction","Generated_ProtectionTrigger","ProtectionFloorBoundary","EmergencyProtectionIcon","ProtectionSignSupport","ProtectionWorldIndicator","EmergencyPoster","EvacuationMap","FireExtinguisher","ElectricalPanel","BackpackEquipmentCounter","TerminalRouteSign","ExitDirectionSign","ExitDoorFrame"})
            if(!all.Any(g=>g.name==required))Error(path+": Level01 interior element missing: "+required);
        var zones=all.SelectMany(g=>g.GetComponents<EarthquakeProtectionTrigger>()).ToArray();
        if(zones.Length!=1){Error(path+": exactly one earthquake protection trigger is required, including inactive objects.");return;}
        var zone=zones[0];var trigger=zone.GetComponent<BoxCollider>();var player=all.FirstOrDefault(g=>g.CompareTag("Player"));
        if(!zone.isActiveAndEnabled||!zone.gameObject.activeInHierarchy)Error(path+": protection trigger must be active and enabled.");
        if(trigger==null||!trigger.enabled||!trigger.isTrigger)Error(path+": protection collider must be an enabled, separate Is Trigger volume.");
        if(player==null||player.GetComponent<Collider>() is not Collider playerCollider||!EarthquakeProtectionTrigger.AcceptsPlayer(playerCollider))Error(path+": protection trigger does not accept the configured Player.");
        if(zone.gameObject.scene.path!="Assets/Scenes/Level01.unity")Error(path+": protection zone must be inside Level01.");
        if(zone.ObjectiveId!=GameIds.Level01Protect)Error(path+": protection objective ID does not match level01_protect.");
        if(zone.RequiredDwellSeconds<2f)Error(path+": protection dwell time must be at least two seconds.");
        foreach(string field in new[]{"earthquakeController","objectivesManager","notificationUI","player","playerCamera","contextualPrompt","objectiveHint","objectiveIndicator","floorBoundaryRenderer","statusLightRenderer","accentLight"})RequireRef(zone,field,path);
        var desk=all.FirstOrDefault(g=>g.name=="Generated_ProtectionDesk");
        if(desk==null||desk.GetComponentsInChildren<Renderer>(true).Length<6)Error(path+": protection zone requires a recognizable multi-part desk.");
        if(trigger!=null&&player?.GetComponent<CharacterController>() is CharacterController controller&&trigger.size.x<controller.radius*2f+.25f)Error(path+": protection entrance lacks CharacterController diameter plus 0.25 m clearance.");
        if(trigger!=null&&player!=null&&trigger.bounds.Intersects(player.GetComponent<CharacterController>().bounds))Error(path+": protection trigger overlaps the player spawn.");
        if(trigger!=null){var solidOverlap=Physics.OverlapBox(trigger.bounds.center,trigger.bounds.extents*.82f,Quaternion.identity,~0,QueryTriggerInteraction.Ignore).Where(c=>!c.transform.IsChildOf(zone.transform)&&!c.transform.IsChildOf(player.transform)).ToArray();if(solidOverlap.Length>0)Error(path+": blocking collider obstructs protection area: "+string.Join(",",solidOverlap.Select(c=>c.name)));}
        var zoneRoot=all.First(g=>g.name=="Generated_InteriorProtectionZone");var labels=zoneRoot.GetComponentsInChildren<TMPro.TMP_Text>(true);
        foreach(string text in new[]{"ZONA DE PROTECCIÓN","AGÁCHATE, CÚBRETE Y SUJÉTATE"})if(!labels.Any(t=>t.text.Contains(text)))Error(path+": readable protection signage missing: "+text);
        if(labels.Any(t=>t.transform.lossyScale.x>1.1f||t.transform.lossyScale.y>1.1f||t.fontSize>4f))Error(path+": protection world-space text is excessively large.");
        var sign=all.FirstOrDefault(g=>g.name=="Generated_ProtectionSign");if(sign!=null&&Vector3.Dot(-sign.transform.forward,Vector3.back)<.5f)Error(path+": protection sign faces away from the starting room.");
        var door=all.FirstOrDefault(g=>g.name=="InitialDoor");if(sign!=null&&door!=null&&sign.GetComponentsInChildren<Renderer>(true).Any(a=>door.GetComponentsInChildren<Renderer>(true).Any(b=>a.bounds.Intersects(b.bounds))))Error(path+": protection signage overlaps the starting door bounds.");
        if(!EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Light)||!EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Moderate)||!EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Strong)||EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Preparing)||EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Inactive)||EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Decreasing)||EarthquakeProtectionTrigger.IsEligibleState(EarthquakeState.Finished))Error(path+": protection eligibility policy is unsafe.");
        var quake=all.SelectMany(g=>g.GetComponents<EarthquakeController>()).SingleOrDefault();if(quake==null||!quake.HasFailureRecovery)Error(path+": earthquake Finished requires a configured success/failure recovery path.");
        var objectives=all.SelectMany(g=>g.GetComponents<ObjectivesManager>()).Single();if(!objectives.Objectives.Any(o=>o.Id==GameIds.Level01ExitRoom&&o.Description=="Sal de la habitación."))Error(path+": objective sequence must include Sal de la habitación after protection.");
        var startDoor=door?.GetComponent<DoorController>();if(startDoor==null)Error(path+": starting door controller missing.");else{foreach(string field in new[]{"doorLeaf","blockingCollider","earthquakeController","objectivesManager"})RequireRef(startDoor,field,path);var doorSo=new SerializedObject(startDoor);if(doorSo.FindProperty("objectiveId")?.stringValue!=GameIds.Level01ExitRoom)Error(path+": starting door is not gated by Sal de la habitación.");}
        if(zone.IsHighlighted)Error(path+": protection zone must be authored without an active highlight.");var indicator=all.FirstOrDefault(g=>g.name=="ProtectionWorldIndicator");if(indicator!=null&&indicator.activeSelf)Error(path+": protection indicator must be authored inactive and hide after resolution.");
        var floor=all.FirstOrDefault(g=>g.name=="Collision_ContinuousFloor")?.GetComponent<BoxCollider>();if(floor==null||floor.size.z<20)Error(path+": continuous Level01 floor collision missing.");
        if(player!=null&&(player.transform.position.x<=-6.2f||player.transform.position.x>=6.2f||player.transform.position.z<=-1.8f||player.transform.position.z>=4.8f))Error(path+": player does not start inside the operations room.");
        foreach(string visual in new[]{"EmergencyPoster","EvacuationMap","BackpackEquipmentCounter","EvacuationTerminal"}){var go=all.FirstOrDefault(g=>g.name==visual);if(go!=null&&go.GetComponentsInChildren<Renderer>(true).Length<1)Error(path+": required interior visual has no renderer: "+visual);}
    }
    private static void ValidateLookController(GameObject player,string path){var look=player.GetComponent<PlayerLookController>();if(look==null)return;if(look.MouseSensitivity<PlayerLookController.MinimumSensitivity||look.MouseSensitivity>PlayerLookController.MaximumSensitivity)Error(path+": GameplayPlayer PlayerLookController mouse sensitivity is invalid; use 0.25..4.0.");if(look.MinimumPitch>-80f||look.MaximumPitch<80f||look.MinimumPitch>=look.MaximumPitch)Error(path+": GameplayPlayer PlayerLookController pitch limits are invalid; recommended -85..85.");if(look.CameraHeightPivot==null||look.CameraLookPivot==null||look.CameraShakePivot==null||look.MainCamera==null)Error(path+": GameplayPlayer PlayerLookController pivot or MainCamera reference is null.");else if(look.CameraLookPivot.parent!=look.CameraHeightPivot||look.CameraShakePivot.parent!=look.CameraLookPivot||look.MainCamera.transform.parent!=look.CameraShakePivot)Error(path+": camera hierarchy must be CameraHeightPivot/CameraLookPivot/CameraShakePivot/Main Camera.");var input=player.GetComponent<PlayerInput>();var action=input?.actions?.FindAction("Look",false);if(action==null)Error(path+": PlayerInput Look action is missing.");else{if(!action.bindings.Any(b=>b.effectivePath=="<Pointer>/delta"||b.effectivePath=="<Mouse>/delta"))Error(path+": Look action requires Mouse delta binding.");if(!action.bindings.Any(b=>b.effectivePath=="<Gamepad>/rightStick"))Error(path+": Look action requires Gamepad rightStick binding.");}}
    private static void ValidateUi(GameObject[] all,string path){var sliders=all.SelectMany(g=>g.GetComponents<Slider>()).ToArray();if(sliders.Length!=2)Error(path+": expected sensitivity and volume sliders.");foreach(var slider in sliders){foreach(string child in new[]{"Fill Area","Fill","Handle Slide Area","Handle"})if(!slider.GetComponentsInChildren<Transform>(true).Any(t=>t.name==child))Error(path+": "+slider.name+" missing "+child);if(slider.fillRect==null||slider.handleRect==null||slider.direction!=Slider.Direction.LeftToRight)Error(path+": "+slider.name+" fill/handle/direction invalid.");else if(Mathf.Abs(slider.handleRect.anchoredPosition.y)>.01f)Error(path+": "+slider.name+" handle is vertically misaligned.");}
        var inventory=all.SelectMany(g=>g.GetComponents<InventoryUI>()).SingleOrDefault();if(inventory==null)Error(path+": InventoryUI missing.");else{var so=new SerializedObject(inventory);var slots=so.FindProperty("slots");if(slots==null||slots.arraySize!=3)Error(path+": inventory requires three unique item slots.");else for(int i=0;i<slots.arraySize;i++){var slot=slots.GetArrayElementAtIndex(i).objectReferenceValue as InventorySlotView;if(slot==null)Error(path+": inventory slot reference missing.");else{foreach(string field in new[]{"icon","itemName","checkMark","accent"})RequireRef(slot,field,path);var icon=new SerializedObject(slot).FindProperty("icon")?.objectReferenceValue as Image;if(icon==null||icon.sprite==null)Error(path+": "+slot.name+" requires a recognizable icon.");}}}if(all.SelectMany(g=>g.GetComponents<TMPro.TMP_Text>()).Any(t=>t.text.Trim()=="x0"))Error(path+": unique inventory items must not display x0.");
        var results=all.SelectMany(g=>g.GetComponents<SimulationResultsUI>()).SingleOrDefault();if(results==null)Error(path+": structured SimulationResultsUI missing.");else foreach(string field in new[]{"totalTimeValue","scoreValue","gradeValue","level01Value","level02Value","incorrectValue","hazardsValue","pausesValue","bestTimeValue"})RequireRef(results,field,path);var pause=all.FirstOrDefault(g=>g.name=="PausePanel");var completion=all.FirstOrDefault(g=>g.name=="CompletionPanel");if(pause==null||completion==null||pause.activeSelf||completion.activeSelf)Error(path+": pause/completion panels must exist and start inactive.");else if(pause.GetComponent<Image>()==null||!pause.GetComponent<Image>().raycastTarget||completion.GetComponent<Image>()==null||!completion.GetComponent<Image>().raycastTarget)Error(path+": modal overlays must block background raycasts.");var hud=all.FirstOrDefault(g=>g.name=="HUD");if(hud!=null&&hud.GetComponentsInChildren<Graphic>(true).Any(g=>g.gameObject.activeInHierarchy&&g.raycastTarget))Error(path+": active gameplay HUD graphics must not block mouse look.");var settings=all.SelectMany(g=>g.GetComponents<GameplaySettingsController>()).SingleOrDefault();if(settings==null)Error(path+": GameplaySettingsController missing.");else foreach(string field in new[]{"researchToggle","researchExplanation"})RequireRef(settings,field,path);}
    private static void ValidatePlayer(GameObject player,string path){var c=player.GetComponent<CharacterController>();if(c==null)Error(path+": CharacterController missing.");else{if(c.height<1.7f||c.radius<.3f||c.skinWidth<.03f||c.skinWidth>c.radius*.5f||c.stepOffset<=0||c.stepOffset>=c.height||c.slopeLimit<30||c.minMoveDistance>.01f)Error(path+": CharacterController settings are unsafe.");float bottom=player.transform.position.y+c.center.y-c.height*.5f;if(bottom<-.02f)Error(path+": player spawn intersects ground.");var overlaps=Physics.OverlapCapsule(player.transform.position+c.center+Vector3.up*(-c.height*.5f+c.radius),player.transform.position+c.center+Vector3.up*(c.height*.5f-c.radius),c.radius*.9f,~0,QueryTriggerInteraction.Ignore);if(overlaps.Any(x=>x.gameObject!=player&&!x.transform.IsChildOf(player.transform)))Error(path+": player spawn overlaps solid geometry: "+string.Join(",",overlaps.Select(x=>x.name)));}var crouch=player.GetComponent<PlayerCrouchController>();if(crouch==null)Error(path+": crouch controller missing.");else if(crouch.StandingHeight>0&&(crouch.CrouchingHeight>=crouch.StandingHeight||crouch.CrouchingHeight<2*c.radius))Error(path+": crouch heights invalid.");if(player.GetComponents<PlayerInput>().Length!=1||player.GetComponents<StarterAssetsInputs>().Length!=1||player.GetComponents<FirstPersonController>().Length!=1||player.GetComponents<GameplayStateController>().Length!=1)Error(path+": duplicate input/movement/state components on player.");var fpc=player.GetComponent<FirstPersonController>();if(fpc!=null&&(fpc.GroundLayers.value&(1<<player.layer))!=0)Error(path+": GroundLayers include Player layer.");}
    private static void ValidateSameSceneReferences(Scene scene,GameObject[] all){foreach(var b in all.SelectMany(g=>g.GetComponents<MonoBehaviour>()).Where(x=>x!=null)){var so=new SerializedObject(b);var p=so.GetIterator();while(p.NextVisible(true)){if(p.propertyType!=SerializedPropertyType.ObjectReference||p.objectReferenceValue==null)continue;if(p.objectReferenceValue is Component c&&c.gameObject.scene.IsValid()&&c.gameObject.scene!=scene)Error(scene.path+": cross-scene reference "+b.name+"."+p.propertyPath);if(p.objectReferenceValue is GameObject g&&g.scene.IsValid()&&g.scene!=scene)Error(scene.path+": cross-scene reference "+b.name+"."+p.propertyPath);}}}
    private static void ValidateButtons(GameObject[] all,string path,string[] names){foreach(string n in names){var buttons=all.Where(g=>g.name==n).SelectMany(g=>g.GetComponents<Button>()).ToArray();if(buttons.Length==0)Error(path+": missing button "+n);else if(buttons.All(b=>b.onClick.GetPersistentEventCount()==0))Error(path+": button not wired: "+n);}}
    private static void RequireText(GameObject[] all,string value,string path){if(!all.SelectMany(g=>g.GetComponents<TMPro.TMP_Text>()).Any(t=>t.text.Contains(value)))Error(path+": required Spanish/UI text missing: "+value);}
    private static void RequireRef(UnityEngine.Object target,string field,string path){if(target==null){Error(path+": missing target for reference "+field);return;}var p=new SerializedObject(target).FindProperty(field);if(p==null||p.objectReferenceValue==null)Error(path+": null serialized reference "+target.GetType().Name+"."+field);}
    private static void Need<T>(GameObject[] all,string path)where T:Component{if(!all.Any(g=>g.GetComponent<T>()!=null))Error(path+": missing "+typeof(T).Name);}
    private static void Exactly<T>(GameObject[] all,string path)where T:Component{int n=all.Sum(g=>g.GetComponents<T>().Length);if(n!=1)Error(path+$": expected exactly one {typeof(T).Name}, found {n}.");}
    private static void NeedAsset(string p){if(!System.IO.File.Exists(p)&&AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(p)==null)Error("Missing required asset: "+p);}
    private static void ValidateItem(string file,string id){var a=AssetDatabase.LoadAssetAtPath<InventoryItemDefinition>($"Assets/ScriptableObjects/Items/{file}.asset");if(a!=null&&a.Id!=id)Error($"{file}: expected ID {id}, got {a.Id}.");}
    private static void Error(string e)=>Errors.Add(e);
}
