using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public static class GuardianMistiScreenshotCapture
{
    private const string Output="Artifacts/Screenshots";
    [MenuItem("Guardian Misti/Capture Review Screenshots")]
    public static void CaptureScreenshots()
    {
        Directory.CreateDirectory(Output);
        CaptureCanvas("Assets/Scenes/MainMenu.unity","MainMenu");
        CaptureScene("Assets/Scenes/Level01.unity",new[]{new Shot("Level01_StartingView",new Vector3(0,1.65f,.3f),new Vector3(0,1.35f,4.7f)),new Shot("Level01_FullRoom",new Vector3(0,3.25f,4.25f),new Vector3(0,1.15f,.15f)),new Shot("Level01_ProtectionArea",new Vector3(-.4f,1.55f,1.2f),new Vector3(-3.2f,.85f,1.35f)),new Shot("Level01_ProtectionDesk",new Vector3(-.5f,1.75f,.1f),new Vector3(-3.2f,1.05f,1.35f)),new Shot("Level01_EmergencyPoster",new Vector3(-1.65f,2.1f,2.9f),new Vector3(-1.65f,2.15f,4.79f)),new Shot("Level01_BackpackArea",new Vector3(1.3f,1.65f,7.1f),new Vector3(-1.75f,1,8.15f)),new Shot("Level01_EvacuationTerminal",new Vector3(0,1.65f,10.5f),new Vector3(2.35f,1,12.2f)),new Shot("Level01_ExitCorridor",new Vector3(0,1.7f,13.5f),new Vector3(0,1.7f,19f)),new Shot("Asset_Backpack",new Vector3(-1.75f,1.45f,7.05f),new Vector3(-1.75f,1.05f,8.15f)),new Shot("Asset_Door",new Vector3(0,1.55f,2.7f),new Vector3(0,1.45f,5)),new Shot("Asset_Desk",new Vector3(3.9f,1.45f,1.55f),new Vector3(3.9f,.65f,-.45f)),new Shot("Asset_Terminal",new Vector3(.4f,1.45f,10.7f),new Vector3(2.35f,1,12.2f))});
        CaptureHudState("Assets/Scenes/Level01.unity","HUD_Normal",false);CaptureEarthquakeTimeline("Assets/Scenes/Level01.unity");CaptureHudState("Assets/Scenes/Level01.unity","Inventory_Empty",false);CaptureHudState("Assets/Scenes/Level01.unity","Inventory_Backpack",true);
        CaptureScene("Assets/Scenes/Level02.unity",new[]{new Shot("Level02_Entry",new Vector3(0,1.7f,.5f),new Vector3(0,1,6)),new Shot("Level02_Radio",new Vector3(0,1.8f,3),new Vector3(-3,.7f,5)),new Shot("Level02_AccessKey",new Vector3(0,1.8f,7),new Vector3(3,.7f,9)),new Shot("Level02_Beacon",new Vector3(0,2,9),new Vector3(0,1.6f,13)),new Shot("Level02_SafeZone",new Vector3(0,2,15),new Vector3(0,1,19)),new Shot("Asset_Radio",new Vector3(-1.8f,1.35f,3.7f),new Vector3(-3,.7f,5)),new Shot("Asset_AccessKey",new Vector3(1.8f,1.3f,7.7f),new Vector3(3,.75f,9)),new Shot("Asset_Beacon",new Vector3(-2.8f,1.8f,11),new Vector3(0,1.5f,13)),new Shot("Asset_SafeZone",new Vector3(-4,2.6f,16),new Vector3(0,.5f,19))});
        CaptureSlider("Assets/Scenes/Level01.unity",.25f,"Sensitivity_Min");CaptureSlider("Assets/Scenes/Level01.unity",1.625f,"Sensitivity_Mid");CaptureSlider("Assets/Scenes/Level01.unity",3f,"Sensitivity_Max");CaptureSlider("Assets/Scenes/Level01.unity",1f,"PausePanel");CaptureCompletion("Assets/Scenes/Level02.unity");
        AssetDatabase.Refresh();Debug.Log("GUARDIAN_MISTI_SCREENSHOTS_SUCCESS: "+Path.GetFullPath(Output));
    }
    private static void CaptureCanvas(string path,string file){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1f;Render(cam,file);}
    private static void CaptureScene(string path,Shot[] shots){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var cam=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Camera>(true)).First();foreach(var shot in shots){cam.transform.position=shot.Position;cam.transform.LookAt(shot.Target);Render(cam,shot.Name);}}
    private static void CaptureEarthquakeTimeline(string path)
    {
        var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1f;var quake=all.Select(t=>t.GetComponent<EarthquakeController>()).First(q=>q!=null);var ui=all.Select(t=>t.GetComponent<EarthquakeUIController>()).First(q=>q!=null);
        quake.BeginSequence();ui.PresentState(quake.State);ui.PresentCountdown("El simulacro comenzará en 3...");Render(cam,"Earthquake_Preparation");Render(cam,"Earthquake_Countdown_3");quake.Tick(1.01f);ui.PresentCountdown("El simulacro comenzará en 2...");Render(cam,"Earthquake_Countdown_2");quake.Tick(1f);ui.PresentCountdown("El simulacro comenzará en 1...");Render(cam,"Earthquake_Countdown_1");quake.Tick(1f);ui.PresentState(quake.State);ui.PresentCountdown("¡SISMO!");Render(cam,"Earthquake_SISMO");
        quake.Tick(.8f);ui.PresentCountdown(string.Empty);ui.PresentState(quake.State);Render(cam,"Earthquake_Light");Render(cam,"Earthquake_Countdown_Hidden");quake.Tick(5f);ui.PresentState(quake.State);Render(cam,"Earthquake_Moderate");foreach(var prop in all.Select(t=>t.GetComponent<EarthquakeReactiveProp>()).Where(p=>p!=null))prop.PreviewReaction(EarthquakeState.Moderate);
        quake.Tick(6f);ui.PresentState(quake.State);Render(cam,"Earthquake_Strong");foreach(var prop in all.Select(t=>t.GetComponent<EarthquakeReactiveProp>()).Where(p=>p!=null))prop.PreviewReaction(EarthquakeState.Strong);cam.transform.position=new Vector3(0,1.8f,.4f);cam.transform.LookAt(new Vector3(5,1.1f,2));Render(cam,"Earthquake_FallenProps");cam.transform.position=new Vector3(0,1.7f,.3f);cam.transform.LookAt(new Vector3(0,1.7f,5));foreach(var ps in all.Select(t=>t.GetComponent<ParticleSystem>()).Where(p=>p!=null))ps.Simulate(3f,true,false,true);Render(cam,"Earthquake_Dust");
        quake.Tick(5f);ui.PresentState(quake.State);Render(cam,"Earthquake_Decreasing");quake.Tick(10f);ui.PresentState(quake.State);Render(cam,"Earthquake_Finished");
    }
    private static void CaptureHudState(string path,string file,bool backpack){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1f;all.First(t=>t.name=="ObjectiveText").GetComponent<TMPro.TMP_Text>().text="Prepárate para el inicio del simulacro.";all.First(t=>t.name=="TimerText").GetComponent<TMPro.TMP_Text>().text="00:42.318";foreach(var slot in all.Select(t=>t.GetComponent<InventorySlotView>()).Where(s=>s!=null))slot.SetObtained(backpack&&slot.ItemId==GameIds.EmergencyBackpack);Render(cam,file);}
    private static void CaptureSlider(string path,float value,string file){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1f;all.First(t=>t.name=="PausePanel").gameObject.SetActive(true);var slider=all.First(t=>t.name=="SensitivitySlider").GetComponent<Slider>();slider.value=value;all.First(t=>t.name=="SensitivityValue").GetComponent<TMPro.TMP_Text>().text=value.ToString("0.00");Render(cam,file);}
    private static void CaptureCompletion(string path){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1f;all.First(t=>t.name=="CompletionPanel").gameObject.SetActive(true);var values=new[]{("TotalTimeValue","03:42.318"),("ScoreValue","920"),("GradeValue","EXCELENTE"),("Level01Value","01:31.240"),("Level02Value","02:11.078"),("IncorrectValue","1"),("HazardsValue","0"),("PausesValue","1"),("BestTimeValue","03:38.901")};foreach(var pair in values)all.First(t=>t.name==pair.Item1).GetComponent<TMPro.TMP_Text>().text=pair.Item2;Render(cam,"CompletionPanel");}
    private static void CaptureHudVariant(string path,string textName,string value,string file){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);var text=all.First(t=>t.name==textName).GetComponent<TMPro.TMP_Text>();text.text=value;text.gameObject.SetActive(true);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=.2f;Render(cam,file);}
    private static void CapturePanel(string path,string panelName,string file){var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true));var cam=all.Select(t=>t.GetComponent<Camera>()).First(c=>c!=null);var canvas=all.Select(t=>t.GetComponent<Canvas>()).First(c=>c!=null);var panel=all.First(t=>t.name==panelName).gameObject;panel.SetActive(true);canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=.2f;Render(cam,file);}
    private static void Render(Camera cam,string name){Canvas.ForceUpdateCanvases();var rt=new RenderTexture(1920,1080,24,RenderTextureFormat.ARGB32);cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(1920,1080,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1920,1080),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(Output,name+".png"),tex.EncodeToPNG());cam.targetTexture=null;RenderTexture.active=null;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);}
    private readonly struct Shot{public readonly string Name;public readonly Vector3 Position,Target;public Shot(string n,Vector3 p,Vector3 t){Name=n;Position=p;Target=t;}}
}
