#if UNITY_INCLUDE_TESTS
using System.Collections.Generic;
using System.Reflection;
using NUnit.Framework;
using StarterAssets;
using TMPro;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using UnityEngine.TestTools;
using System.Collections;

public class GuardianMistiEditModeTests
{
    private readonly List<Object> cleanup=new();
    [TearDown] public void TearDown(){Time.timeScale=1;foreach(var o in cleanup)if(o!=null)Object.DestroyImmediate(o);cleanup.Clear();}
    private InventoryItemDefinition Item(string id){var d=ScriptableObject.CreateInstance<InventoryItemDefinition>();cleanup.Add(d);Set(d,"<Id>k__BackingField",id);Set(d,"<Name>k__BackingField",id);return d;}
    private T Component<T>()where T:Component{var g=new GameObject(typeof(T).Name);cleanup.Add(g);return g.AddComponent<T>();}
    private static void Set(object o,string f,object v)=>o.GetType().GetField(f,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(o,v);
    private static object Invoke(object o,string method,params object[] args)=>o.GetType().GetMethod(method,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(o,args);
    [Test] public void DestroyedUnityObjectUsesUnityNullSemantics(){var g=new GameObject("Gone");Object.DestroyImmediate(g);Assert.True(g==null);Assert.False(ReferenceEquals(g,null));}
    [Test] public void InteractionUiToleratesDestroyedDependenciesAndRepeatedHide(){var ui=Component<InteractionUIController>();var prompt=Component<InteractionPromptUI>();var cross=Component<CrosshairUI>();Set(ui,"promptUI",prompt);Set(ui,"crosshairUI",cross);Object.DestroyImmediate(prompt.gameObject);Assert.DoesNotThrow(ui.Hide);Assert.DoesNotThrow(ui.Hide);}
    [Test] public void PromptHideIsIdempotent(){var g=new GameObject("Prompt");cleanup.Add(g);var text=g.AddComponent<TextMeshProUGUI>();var prompt=g.AddComponent<InteractionPromptUI>();Set(prompt,"promptText",text);prompt.Show("Abrir");Assert.DoesNotThrow(prompt.Hide);Assert.DoesNotThrow(prompt.Hide);Assert.False(g.activeSelf);}
    [Test] public void InventoryRejectsNullAndDuplicatesAndHasItem(){var m=Component<InventoryManager>();Assert.False(m.AddItem(null));var d=Item("one");Assert.True(m.AddItem(new InventoryItem(d)));Assert.False(m.AddItem(new InventoryItem(d)));Assert.True(m.HasItem("one"));Assert.False(m.HasItem(null));}
    [Test] public void ObjectivesProgressOnlyInOrderAndStopAfterCompletion(){var m=Component<ObjectivesManager>();Set(m,"objectives",new List<Objective>{new("a","A"),new("b","B")});Assert.False(m.TryCompleteObjective("b"));Assert.True(m.TryCompleteObjective("a"));Assert.True(m.TryCompleteObjective("b"));Assert.False(m.TryCompleteObjective("b"));}
    [Test] public void GameplayInputPauseResumeAndCompletionAreCentralized(){var g=new GameObject("Player");cleanup.Add(g);g.AddComponent<CharacterController>();var inputs=g.AddComponent<StarterAssetsInputs>();var pi=g.AddComponent<PlayerInput>();var movement=g.AddComponent<FirstPersonController>();var interaction=g.AddComponent<InteractionSystem>();var state=g.AddComponent<GameplayStateController>();Set(state,"playerInput",pi);Set(state,"movement",movement);Set(state,"starterInputs",inputs);Set(state,"interaction",interaction);state.RequestState(GameplayState.Playing);Assert.True(movement.enabled);Assert.True(interaction.enabled);state.RequestState(GameplayState.Paused);Assert.AreEqual(0,Time.timeScale);Assert.False(movement.enabled);Assert.False(interaction.enabled);state.RequestState(GameplayState.Playing);Assert.AreEqual(1,Time.timeScale);Assert.True(movement.enabled);state.RequestState(GameplayState.Completed);Assert.AreEqual(GameplayState.Completed,state.State);Assert.False(movement.enabled);Assert.False(state.RequestState(GameplayState.Paused));Assert.AreEqual(GameplayState.Completed,state.State);}
    [Test] public void SceneConstantsAreStable(){Assert.AreEqual("MainMenu",SceneNames.MainMenu);Assert.AreEqual("Level01",SceneNames.Level01);Assert.AreEqual("Level02",SceneNames.Level02);}
    [Test] public void BeaconRequiresRadioAndKey(){var inv=Component<InventoryManager>();var beacon=Component<EmergencyBeaconController>();Assert.False(beacon.HasRequirements(inv));inv.AddItem(new InventoryItem(Item(GameIds.EmergencyRadio)));Assert.False(beacon.HasRequirements(inv));inv.AddItem(new InventoryItem(Item(GameIds.AccessKey)));Assert.True(beacon.HasRequirements(inv));}
    [Test] public void SceneLoaderRejectsRepeatedInvalidRequestsAndKeepsTimeScale(){var loader=Component<SceneLoader>();Time.timeScale=0;Assert.False(loader.TryLoadScene((GameScene)999));Assert.False(loader.TryLoadScene((GameScene)999));Assert.AreEqual(0,Time.timeScale);}
    [Test] public void TimerFormattingIsStable(){Assert.AreEqual("01:05.250",SimulationSession.FormatTime(65.25f));}
    [Test] public void ScorePenaltiesAreTransparent(){Assert.AreEqual(1000,PerformanceScoreCalculator.Calculate(90,0,0,0,0));Assert.Less(PerformanceScoreCalculator.Calculate(120,2,1,1,4),1000);Assert.AreEqual("Excelente",PerformanceScoreCalculator.Grade(950));}
    [Test] public void EarthquakeCurveIsBounded(){var p=ScriptableObject.CreateInstance<EarthquakeProfile>();cleanup.Add(p);Assert.That(p.Evaluate(0),Is.InRange(0f,1f));Assert.That(p.Evaluate(999),Is.InRange(0f,1f));}
    [Test] public void GameplayStateCompletionHasPriority(){var state=Component<GameplayStateController>();state.RequestState(GameplayState.Playing);state.RequestState(GameplayState.Completed);Assert.False(state.RequestState(GameplayState.Paused));Assert.AreEqual(GameplayState.Completed,state.State);}
    [Test] public void GameplayStatePauseAndResumeSelectInputPolicy(){var g=new GameObject("StatePlayer");cleanup.Add(g);g.AddComponent<CharacterController>();var inputs=g.AddComponent<StarterAssetsInputs>();var pi=g.AddComponent<PlayerInput>();var move=g.AddComponent<FirstPersonController>();var interaction=g.AddComponent<InteractionSystem>();var state=g.AddComponent<GameplayStateController>();Set(state,"playerInput",pi);Set(state,"movement",move);Set(state,"starterInputs",inputs);Set(state,"interaction",interaction);state.RequestState(GameplayState.Paused);Assert.False(inputs.cursorInputForLook);Assert.False(move.enabled);state.RequestState(GameplayState.Playing);Assert.True(inputs.cursorInputForLook);Assert.True(move.enabled);}
    [Test] public void JumpGateConsumesHeldInputUntilRelease(){var gate=Component<JumpInputGate>();Assert.True(gate.EvaluatePress(true));Assert.False(gate.EvaluatePress(true));Assert.False(gate.EvaluatePress(false));Assert.True(gate.EvaluatePress(true));}
    [Test] public void ObstructionDetectorRequiresSustainedValidInput(){Assert.True(GameplayRuntimeLogger.ShouldReportObstruction(Vector2.up,GameplayState.Playing,true,true,0,.6f));Assert.False(GameplayRuntimeLogger.ShouldReportObstruction(Vector2.up,GameplayState.Paused,true,true,0,.6f));Assert.False(GameplayRuntimeLogger.ShouldReportObstruction(Vector2.up,GameplayState.Playing,true,true,.1f,.6f));}
    [Test] public void DuplicateSessionKeepsOriginalInstance(){var first=Component<SimulationSession>();Invoke(first,"Awake");var duplicate=Component<SimulationSession>();Invoke(duplicate,"Awake");Assert.AreSame(first,SimulationSession.Instance);Assert.AreNotSame(duplicate,SimulationSession.Instance);}
    [Test] public void NestedSessionDetachesBeforePersistence(){var parent=new GameObject("Parent");cleanup.Add(parent);var child=new GameObject("Session");cleanup.Add(child);child.transform.SetParent(parent.transform);var session=child.AddComponent<SimulationSession>();Invoke(session,"Awake");Assert.IsNull(session.transform.parent);}
    [Test] public void NewRunResetClearsMetrics(){var session=Component<SimulationSession>();session.RecordHazard();session.RecordPause();session.RecordObjective("a");session.ResetRun();Assert.AreEqual(0,session.HazardContacts);Assert.AreEqual(0,session.Pauses);Assert.IsEmpty(session.ObjectiveTimestamps);Assert.False(session.IsRunning);}
    [Test] public void SessionMetricsRemainContinuousUntilReset(){var session=Component<SimulationSession>();session.RecordObjective("level01");session.RecordHazard();session.RecordObjective("level02");Assert.AreEqual(1,session.HazardContacts);CollectionAssert.AreEqual(new[]{"level01:0.000","level02:0.000"},session.ObjectiveTimestamps);}
    [Test] public void SessionIsDestroyedOnMainMenu(){var session=Component<SimulationSession>();Invoke(session,"Awake");session.HandleSceneLoaded(SceneNames.MainMenu);Assert.True(session==null);}
    [Test] public void EarthquakeCountdownAndStartBannerAreOrdered(){var q=Quake(3,4);var messages=new List<string>();q.CountdownChanged+=messages.Add;Assert.True(q.BeginSequence());q.Tick(1.01f);q.Tick(1f);q.Tick(1f);CollectionAssert.AreEqual(new[]{"El simulacro comenzará en 3...","El simulacro comenzará en 2...","El simulacro comenzará en 1...","¡SISMO!"},messages);Assert.AreEqual(EarthquakeState.Light,q.State);}
    [Test] public void EarthquakeStatesAreOrdered(){var q=Quake(0,4);var states=new List<EarthquakeState>();q.StateChanged+=states.Add;q.BeginSequence();q.Tick(.01f);q.Tick(1f);q.Tick(1f);q.Tick(1f);q.Tick(1f);CollectionAssert.IsSubsetOf(new[]{EarthquakeState.Preparing,EarthquakeState.Light,EarthquakeState.Moderate,EarthquakeState.Strong,EarthquakeState.Decreasing,EarthquakeState.Finished},states);Assert.AreEqual(EarthquakeState.Finished,q.State);}
    [Test] public void PauseFreezesAndResumeContinuesCountdown(){var q=Quake(3,4);q.BeginSequence();q.Tick(0f);Assert.AreEqual(3,q.DisplayedCountdown);q.Tick(1.01f);Assert.AreEqual(2,q.DisplayedCountdown);}
    [Test] public void TimerStartsOnlyAfterCountdown(){var s=Component<SimulationSession>();Invoke(s,"Awake");var q=Quake(3,4);q.BeginSequence();Assert.False(s.IsRunning);q.Tick(2.9f);Assert.False(s.IsRunning);q.Tick(.2f);Assert.True(s.IsRunning);}
    [Test] public void EarthquakeRejectsDuplicateStartAndResetRestoresInactive(){var q=Quake(3,4);Assert.True(q.BeginSequence());Assert.False(q.BeginSequence());q.ResetSequence();Assert.AreEqual(EarthquakeState.Inactive,q.State);Assert.True(q.BeginSequence());}
    [Test] public void EarthquakeUiHidesCountdownAfterCompletion(){var q=Quake(0,.01f);var text=Component<TextMeshProUGUI>();var intensity=Component<TextMeshProUGUI>();var ui=Component<EarthquakeUIController>();Set(ui,"earthquakeController",q);Set(ui,"countdownText",text);Set(ui,"intensityText",intensity);ui.PresentCountdown("¡SISMO!");Assert.True(ui.CountdownVisible);ui.PresentState(EarthquakeState.Finished);Assert.False(ui.CountdownVisible);Assert.AreEqual("Sismo finalizado",intensity.text);}
    [Test] public void EarthquakeWithoutDustAndDestroyAreSafe(){var q=Quake(0,.01f);q.BeginSequence();Assert.DoesNotThrow(()=>q.Tick(.1f));Assert.DoesNotThrow(()=>Object.DestroyImmediate(q.gameObject));}
    [Test] public void CameraOffsetResetsAndPlayerTransformIsUnaffected(){var player=new GameObject("PlayerProbe");cleanup.Add(player);player.transform.position=new Vector3(2,3,4);var camera=new GameObject("Presentation");cleanup.Add(camera);camera.transform.SetParent(player.transform);camera.transform.localPosition=new Vector3(0,1,0);var q=Quake(0,2);Set(q,"cameraEffectRoot",camera.transform);q.BeginSequence();q.Tick(.01f);q.Tick(1f);Assert.AreEqual(new Vector3(2,3,4),player.transform.position);q.Tick(2f);Assert.Less(Vector3.Distance(camera.transform.localPosition,new Vector3(0,1,0)),.0001f);}
    [Test] public void ReactivePropAcceptsOnlyStagedBoundedImpulses(){var go=new GameObject("Prop");cleanup.Add(go);go.AddComponent<BoxCollider>();go.AddComponent<Rigidbody>();var prop=go.AddComponent<EarthquakeReactiveProp>();Invoke(prop,"Awake");Assert.False(prop.React(EarthquakeState.Light,2));Assert.True(prop.React(EarthquakeState.Moderate,2));Assert.False(prop.React(EarthquakeState.Moderate,2));Assert.True(prop.React(EarthquakeState.Strong,2));Assert.False(prop.React(EarthquakeState.Finished,2));Assert.DoesNotThrow(prop.StopForces);}
    [Test] public void ProfileDefinesAllPresentationCurvesAndSafeLimits(){var p=ScriptableObject.CreateInstance<EarthquakeProfile>();cleanup.Add(p);Assert.NotNull(p.CameraShakeCurve);Assert.NotNull(p.AudioVolumeCurve);Assert.NotNull(p.LightFlickerCurve);Assert.NotNull(p.DustEmissionCurve);Assert.NotNull(p.PropForceCurve);Assert.That(p.MaximumActivePhysicsProps,Is.InRange(1,8));Assert.LessOrEqual(p.LightFlickerIntensity,.35f);}
    [Test] public void ProtectionMetricsRecordFirstArrivalAndStrongExposure(){var s=Component<SimulationSession>();s.RecordStrongOutside(1.25f);s.RecordProtection(2.5f);s.RecordProtection(8f);Assert.True(s.ProtectionReached);Assert.AreEqual(2.5f,s.TimeToProtection);Assert.AreEqual(1.25f,s.StrongPhaseOutsideTime);}
    [Test] public void OptionalEarthquakeAudioAndSceneUnloadAreSafe(){var q=Quake(0,.2f);q.BeginSequence();Assert.DoesNotThrow(()=>q.Tick(.1f));Assert.DoesNotThrow(()=>Invoke(q,"OnDisable"));Assert.DoesNotThrow(()=>Object.DestroyImmediate(q.gameObject));}
    private EarthquakeController Quake(float countdown,float duration){var q=Component<EarthquakeController>();var p=ScriptableObject.CreateInstance<EarthquakeProfile>();cleanup.Add(p);Set(p,"<PreparationCountdown>k__BackingField",countdown);Set(p,"<Duration>k__BackingField",duration);Set(q,"profile",p);return q;}
}
#endif
