using System;
using System.Collections.Generic;
using System.Linq;
using StarterAssets;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public static class GuardianMistiProjectValidator
{
    private static readonly List<string> Errors=new();
    private static readonly string[] Scenes={"Assets/Scenes/MainMenu.unity","Assets/Scenes/Level01.unity","Assets/Scenes/Level02.unity"};
    private static readonly string[] Prefabs={"Assets/Prefabs/Player/GameplayPlayer.prefab","Assets/Prefabs/UI/GameplayHUD.prefab","Assets/Prefabs/Systems/GameplaySystems.prefab","Assets/Prefabs/Gameplay/InteractableDoor.prefab","Assets/Prefabs/Gameplay/CollectibleItem.prefab","Assets/Prefabs/Gameplay/LevelExit.prefab","Assets/Prefabs/Gameplay/SafeZone.prefab","Assets/Prefabs/Gameplay/EvacuationTerminal.prefab","Assets/Prefabs/Gameplay/EmergencyBeacon.prefab","Assets/Prefabs/Gameplay/EmergencyBackpack.prefab","Assets/Prefabs/Gameplay/EmergencyRadio.prefab","Assets/Prefabs/Gameplay/AccessKey.prefab","Assets/Prefabs/Environment/FacilityModule.prefab","Assets/Prefabs/Environment/KenneyDesk.prefab","Assets/Prefabs/Environment/KenneyChair.prefab","Assets/Prefabs/Environment/KenneyShelf.prefab","Assets/Prefabs/Environment/KenneyDoorFrame.prefab","Assets/Prefabs/Environment/KenneyRock.prefab","Assets/Prefabs/Environment/KenneySignpost.prefab","Assets/Prefabs/Environment/KenneyRescueTent.prefab"};
    [MenuItem("Guardian Misti/Validate Project")]
    public static void ValidateProject()
    {
        Errors.Clear();Time.timeScale=1f;
        foreach(string p in Scenes.Concat(Prefabs))NeedAsset(p);
        foreach(string p in new[]{"Assets/ScriptableObjects/Items/EmergencyBackpack.asset","Assets/ScriptableObjects/Items/EmergencyRadio.asset","Assets/ScriptableObjects/Items/AccessKey.asset","Assets/Settings/GuardianMisti/MainMenuVolume.asset","Assets/Settings/GuardianMisti/Level01Volume.asset","Assets/Settings/GuardianMisti/Level02Volume.asset"})NeedAsset(p);
        foreach(string p in new[]{"Assets/ThirdParty/Kenney/FurnitureKit/Models/desk.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/chairDesk.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/bookcaseOpen.fbx","Assets/ThirdParty/Kenney/FurnitureKit/Models/doorway.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/rock-a.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/signpost.fbx","Assets/ThirdParty/Kenney/SurvivalKit/Models/tent-canvas.fbx","Assets/ThirdParty/ATTRIBUTION.md","Artifacts/ExternalAssetManifest.json"})NeedAsset(p);
        var enabled=EditorBuildSettings.scenes.Where(s=>s.enabled).Select(s=>s.path).ToArray();if(!enabled.SequenceEqual(Scenes))Error("Build scenes must be MainMenu, Level01, Level02 only and in order.");
        ValidateItem("EmergencyBackpack",GameIds.EmergencyBackpack);ValidateItem("EmergencyRadio",GameIds.EmergencyRadio);ValidateItem("AccessKey",GameIds.AccessKey);
        ValidateScene(Scenes[0],false,false);ValidateScene(Scenes[1],true,false);ValidateScene(Scenes[2],true,true);
        if(Errors.Count>0){foreach(string e in Errors)Debug.LogError("VALIDATION: "+e);throw new Exception($"Guardian Misti validation failed with {Errors.Count} actionable error(s).");}
        Debug.Log("GUARDIAN_MISTI_VALIDATION_SUCCESS");
    }
    private static void ValidateScene(string path,bool gameplay,bool final)
    {
        if(!System.IO.File.Exists(path))return;var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var roots=scene.GetRootGameObjects();var all=roots.SelectMany(r=>r.GetComponentsInChildren<Transform>(true)).Select(t=>t.gameObject).ToArray();
        if(roots.Count(r=>r.name=="Generated_GuardianMisti")!=1)Error(path+": exactly one Generated_GuardianMisti root is required.");
        Exactly<EventSystem>(all,path);Exactly<AudioListener>(all,path);Need<Canvas>(all,path);Need<SceneLoader>(all,path);
        var es=all.SelectMany(g=>g.GetComponents<InputSystemUIInputModule>()).ToArray();if(es.Length!=1)Error(path+": EventSystem must use exactly one InputSystemUIInputModule.");
        foreach(var go in all){if(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(go)>0)Error(path+": Missing Script on "+go.name);foreach(var r in go.GetComponents<Renderer>()){if(r.sharedMaterials.Any(m=>m==null))Error(path+": renderer has missing material on "+go.name);foreach(var m in r.sharedMaterials)if(m!=null&&(m.shader==null||m.shader.name.Contains("Error")))Error(path+": invalid/pink shader on "+go.name);}}
        ValidateSameSceneReferences(scene,all);
        var scaler=all.SelectMany(g=>g.GetComponents<CanvasScaler>()).FirstOrDefault();if(scaler==null||scaler.uiScaleMode!=CanvasScaler.ScaleMode.ScaleWithScreenSize)Error(path+": CanvasScaler must use Scale With Screen Size.");
        var sessions=all.SelectMany(g=>g.GetComponents<SimulationSession>()).ToArray();if(!gameplay&&sessions.Length>0)Error(path+": MainMenu must not contain SimulationSession.");if(gameplay&&final&&sessions.Length>0)Error(path+": Level02 must receive the persistent session from Level01, not define another one.");if(gameplay&&!final){if(sessions.Length!=1)Error(path+": Level01 requires exactly one SimulationSession.");else{if(sessions[0].transform.parent!=null)Error(path+": SimulationSession must be a scene-root object.");var sessionSo=new SerializedObject(sessions[0]);var iterator=sessionSo.GetIterator();while(iterator.NextVisible(true))if(iterator.propertyType==SerializedPropertyType.ObjectReference&&iterator.objectReferenceValue is Component component&&component.gameObject.scene==scene)Error(path+": SimulationSession must not serialize scene-local references.");}}
        if(!gameplay){Need<MainMenuController>(all,path);RequireText(all,"GUARDIAN MISTI",path);RequireText(all,"INICIAR SIMULACIÓN",path);RequireText(all,"INSTRUCCIONES",path);RequireText(all,"SALIR",path);ValidateButtons(all,path,new[]{"PlayButton","InstructionsButton","ExitButton"});return;}
        Exactly<PlayerInput>(all,path);Exactly<StarterAssetsInputs>(all,path);Exactly<FirstPersonController>(all,path);Exactly<GameplayStateController>(all,path);Exactly<InteractionSystem>(all,path);Exactly<InteractionUIController>(all,path);Need<ObjectivesManager>(all,path);Need<InventoryManager>(all,path);Need<PauseController>(all,path);Need<GameplayCursorController>(all,path);Exactly<GameplayDiagnostics>(all,path);Exactly<GameplayDiagnosticsOverlay>(all,path);Exactly<GameplayRuntimeLogger>(all,path);Exactly<Camera>(all,path);
        var player=all.FirstOrDefault(g=>g.name=="GameplayPlayer");if(player==null||!player.CompareTag("Player"))Error(path+": GameplayPlayer missing or not tagged Player.");else ValidatePlayer(player,path);
        if(all.Count(g=>g.CompareTag("MainCamera")&&g.activeInHierarchy)!=1)Error(path+": expected exactly one active MainCamera tag.");var input=all.SelectMany(g=>g.GetComponents<PlayerInput>()).SingleOrDefault();if(input==null||input.actions==null||input.defaultActionMap!="Player")Error(path+": PlayerInput actions/default Player map are not configured.");
        var interaction=all.SelectMany(g=>g.GetComponents<InteractionSystem>()).SingleOrDefault();RequireRef(interaction,"playerCamera",path);RequireRef(interaction,"interactionUIController",path);
        var ui=all.SelectMany(g=>g.GetComponents<InteractionUIController>()).SingleOrDefault();RequireRef(ui,"promptUI",path);RequireRef(ui,"crosshairUI",path);
        var state=all.SelectMany(g=>g.GetComponents<GameplayStateController>()).SingleOrDefault();foreach(string f in new[]{"playerInput","movement","starterInputs","interaction","pausePanel","completionPanel"})RequireRef(state,f,path);var diagnostics=all.SelectMany(g=>g.GetComponents<GameplayDiagnostics>()).SingleOrDefault();foreach(string f in new[]{"stateController","playerInput","inputs","movement","characterController","interaction","pausePanel","completionPanel","runtimeLogger"})RequireRef(diagnostics,f,path);var overlay=all.SelectMany(g=>g.GetComponents<GameplayDiagnosticsOverlay>()).SingleOrDefault();foreach(string f in new[]{"diagnostics","panel","diagnosticText"})RequireRef(overlay,f,path);ValidateUi(all,path);
        if(!final){var earthquakes=all.SelectMany(g=>g.GetComponents<EarthquakeController>()).ToArray();if(earthquakes.Length!=1)Error(path+": Level01 requires exactly one EarthquakeController.");else{var quake=earthquakes[0];foreach(string f in new[]{"profile","cameraEffectRoot","dust","objectivesManager"})RequireRef(quake,f,path);var quakeUi=all.SelectMany(g=>g.GetComponents<EarthquakeUIController>()).SingleOrDefault();if(quakeUi==null)Error(path+": EarthquakeUIController missing.");else{foreach(string f in new[]{"earthquakeController","countdownText","intensityText"})RequireRef(quakeUi,f,path);var uiSo=new SerializedObject(quakeUi);var countdown=uiSo.FindProperty("countdownText")?.objectReferenceValue as TMPro.TMP_Text;if(countdown!=null&&(!string.IsNullOrEmpty(countdown.text)||countdown.gameObject.activeSelf))Error(path+": countdown must be authored empty and hidden; runtime state owns it.");}var dustProperty=new SerializedObject(quake).FindProperty("dust");var dust=dustProperty?.objectReferenceValue as ParticleSystem;if(dust!=null){var renderer=dust.GetComponent<ParticleSystemRenderer>();if(renderer==null||renderer.sharedMaterial==null||renderer.sharedMaterial.shader==null||renderer.sharedMaterial.shader.name.Contains("Error"))Error(path+": earthquake dust requires a valid URP particle material.");if(dust.emission.rateOverTime.constantMax>7.01f||dust.main.maxParticles>60)Error(path+": earthquake dust emission is excessive.");foreach(var t in dust.GetComponentsInChildren<Transform>(true))if(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject)>0)Error(path+": Missing Script in earthquake dust hierarchy.");}}}
        if(all.Count(g=>g.name=="GlobalVolume")!=1||all.SelectMany(g=>g.GetComponents<Volume>()).All(v=>!v.isGlobal||v.sharedProfile==null))Error(path+": configured project-owned Global Volume required.");
        if(all.SelectMany(g=>g.GetComponents<Light>()).Count()<2)Error(path+": directional plus local guidance lighting required.");
        foreach(var i in all.SelectMany(g=>g.GetComponents<MonoBehaviour>()).Where(m=>m is IInteractable)){if(i.GetComponent<Collider>()==null)Error(path+": interactable without collider: "+i.name);}
        var ids=all.SelectMany(g=>g.GetComponents<ObjectivesManager>()).First().Objectives.Select(o=>o.Id).ToArray();var expected=final?new[]{GameIds.Level02CollectRadio,GameIds.Level02CollectAccessKey,GameIds.Level02ActivateBeacon,GameIds.Level02ReachSafeZone}:new[]{GameIds.Level01Preparation,GameIds.Level01Protect,GameIds.Level01ExitRoom,GameIds.Level01CollectBackpack,GameIds.Level01ActivateEvacuation,GameIds.Level01ReachExit};if(!ids.SequenceEqual(expected))Error(path+": objective IDs/order do not match required flow.");
        ValidateButtons(all,path,new[]{"ResumeButton","RestartButton","MenuButton"});RequireText(all,"SIMULACIÓN EN PAUSA",path);
        if(final){Need<EmergencyBeaconController>(all,path);var zone=all.SelectMany(g=>g.GetComponents<SafeZoneController>()).SingleOrDefault();if(zone==null||zone.GetComponent<Collider>()==null||!zone.GetComponent<Collider>().isTrigger)Error(path+": one-shot SafeZone trigger missing.");ValidateButtons(all,path,new[]{"ExitButton"});RequireText(all,"MISIÓN COMPLETADA",path);}else{var exit=all.SelectMany(g=>g.GetComponents<LevelExitController>()).SingleOrDefault();if(exit==null||exit.GetComponent<Collider>()==null||!exit.GetComponent<Collider>().isTrigger)Error(path+": LevelExit trigger missing.");}
        foreach(string visual in final?new[]{"EmergencyRadio","AccessKey","EmergencyBeacon","RescuePlatform","VolcanicRock","KenneyRockLandmark","KenneyEvacuationSign","KenneyRescueTent"}:new[]{"InitialDoor","EmergencyBackpack","EvacuationTerminal","EmergencySupplyCrate","EmergencyLight","KenneyEmergencyDesk","KenneyOfficeChair","KenneySupplyShelf","KenneyDoorwayDetail"})if(!all.Any(g=>g.name==visual))Error(path+": composed visual missing: "+visual);if(!final)ValidateLevel01Environment(all,path);
    }
    private static void ValidateLevel01Environment(GameObject[] all,string path){foreach(string required in new[]{"Level01FacilityInterior","RoomFloor","RoomCeiling","RoomBackWall","RoomLeftWall","RoomRightWall","ProtectionDesk","ProtectionFloorMarker","EmergencyPoster","EvacuationMap","FireExtinguisher","ElectricalPanel","BackpackEquipmentCounter","TerminalRouteSign","ExitDirectionSign","ExitDoorFrame"})if(!all.Any(g=>g.name==required))Error(path+": Level01 interior element missing: "+required);var walls=all.Count(g=>g.name.StartsWith("Room")&&g.name.Contains("Wall")&&g.GetComponent<Renderer>()!=null);if(walls<5)Error(path+": starting room is not visually enclosed by four walls and a divided doorway wall.");var protection=all.FirstOrDefault(g=>g.name=="InteriorProtectionZone");if(protection==null||protection.GetComponent<Collider>()==null||!protection.GetComponent<Collider>().isTrigger)Error(path+": protection volume must be a separate trigger.");var desk=all.FirstOrDefault(g=>g.name=="ProtectionDesk");if(desk==null||desk.GetComponentsInChildren<Renderer>(true).Length<6)Error(path+": protection point requires a recognizable multi-part desk.");if(protection!=null&&desk!=null&&!desk.GetComponentsInChildren<Renderer>(true).Any(r=>r.bounds.Intersects(protection.GetComponent<Collider>().bounds)))Error(path+": protection trigger is not spatially explained by the desk.");var floor=all.FirstOrDefault(g=>g.name=="Collision_ContinuousFloor")?.GetComponent<BoxCollider>();if(floor==null||floor.size.z<20)Error(path+": continuous Level01 floor collision missing.");var player=all.FirstOrDefault(g=>g.CompareTag("Player"));if(player!=null&&(player.transform.position.x<=-6.2f||player.transform.position.x>=6.2f||player.transform.position.z<=-1.8f||player.transform.position.z>=4.8f))Error(path+": player does not start inside the operations room.");foreach(string visual in new[]{"EmergencyPoster","EvacuationMap","BackpackEquipmentCounter","EvacuationTerminal"}){var go=all.FirstOrDefault(g=>g.name==visual);if(go!=null&&go.GetComponentsInChildren<Renderer>(true).Length<1)Error(path+": required interior visual has no renderer: "+visual);}}
    private static void ValidateUi(GameObject[] all,string path){var sliders=all.SelectMany(g=>g.GetComponents<Slider>()).ToArray();if(sliders.Length!=2)Error(path+": expected sensitivity and volume sliders.");foreach(var slider in sliders){foreach(string child in new[]{"Fill Area","Fill","Handle Slide Area","Handle"})if(!slider.GetComponentsInChildren<Transform>(true).Any(t=>t.name==child))Error(path+": "+slider.name+" missing "+child);if(slider.fillRect==null||slider.handleRect==null||slider.direction!=Slider.Direction.LeftToRight)Error(path+": "+slider.name+" fill/handle/direction invalid.");else if(Mathf.Abs(slider.handleRect.anchoredPosition.y)>.01f)Error(path+": "+slider.name+" handle is vertically misaligned.");}
        var inventory=all.SelectMany(g=>g.GetComponents<InventoryUI>()).SingleOrDefault();if(inventory==null)Error(path+": InventoryUI missing.");else{var so=new SerializedObject(inventory);var slots=so.FindProperty("slots");if(slots==null||slots.arraySize!=3)Error(path+": inventory requires three unique item slots.");else for(int i=0;i<slots.arraySize;i++){var slot=slots.GetArrayElementAtIndex(i).objectReferenceValue as InventorySlotView;if(slot==null)Error(path+": inventory slot reference missing.");else{foreach(string field in new[]{"icon","itemName","checkMark","accent"})RequireRef(slot,field,path);var icon=new SerializedObject(slot).FindProperty("icon")?.objectReferenceValue as Image;if(icon==null||icon.sprite==null)Error(path+": "+slot.name+" requires a recognizable icon.");}}}if(all.SelectMany(g=>g.GetComponents<TMPro.TMP_Text>()).Any(t=>t.text.Trim()=="x0"))Error(path+": unique inventory items must not display x0.");
        var results=all.SelectMany(g=>g.GetComponents<SimulationResultsUI>()).SingleOrDefault();if(results==null)Error(path+": structured SimulationResultsUI missing.");else foreach(string field in new[]{"totalTimeValue","scoreValue","gradeValue","level01Value","level02Value","incorrectValue","hazardsValue","pausesValue","bestTimeValue"})RequireRef(results,field,path);var pause=all.FirstOrDefault(g=>g.name=="PausePanel");var completion=all.FirstOrDefault(g=>g.name=="CompletionPanel");if(pause==null||completion==null||pause.activeSelf||completion.activeSelf)Error(path+": pause/completion panels must exist and start inactive.");else if(pause.GetComponent<Image>()==null||!pause.GetComponent<Image>().raycastTarget||completion.GetComponent<Image>()==null||!completion.GetComponent<Image>().raycastTarget)Error(path+": modal overlays must block background raycasts.");var hud=all.FirstOrDefault(g=>g.name=="HUD");if(hud!=null&&hud.GetComponentsInChildren<Graphic>(true).Any(g=>g.gameObject.activeInHierarchy&&g.raycastTarget))Error(path+": active gameplay HUD graphics must not block mouse look.");}
    private static void ValidatePlayer(GameObject player,string path){var c=player.GetComponent<CharacterController>();if(c==null)Error(path+": CharacterController missing.");else{if(c.height<1.7f||c.radius<.3f||c.skinWidth<.03f||c.skinWidth>c.radius*.5f||c.stepOffset<=0||c.stepOffset>=c.height||c.slopeLimit<30||c.minMoveDistance>.01f)Error(path+": CharacterController settings are unsafe.");float bottom=player.transform.position.y+c.center.y-c.height*.5f;if(bottom<-.02f)Error(path+": player spawn intersects ground.");var overlaps=Physics.OverlapCapsule(player.transform.position+c.center+Vector3.up*(-c.height*.5f+c.radius),player.transform.position+c.center+Vector3.up*(c.height*.5f-c.radius),c.radius*.9f,~0,QueryTriggerInteraction.Ignore);if(overlaps.Any(x=>x.gameObject!=player&&!x.transform.IsChildOf(player.transform)))Error(path+": player spawn overlaps solid geometry: "+string.Join(",",overlaps.Select(x=>x.name)));}if(player.GetComponents<PlayerInput>().Length!=1||player.GetComponents<StarterAssetsInputs>().Length!=1||player.GetComponents<FirstPersonController>().Length!=1||player.GetComponents<GameplayStateController>().Length!=1)Error(path+": duplicate input/movement/state components on player.");var fpc=player.GetComponent<FirstPersonController>();if(fpc!=null&&(fpc.GroundLayers.value&(1<<player.layer))!=0)Error(path+": GroundLayers include Player layer.");}
    private static void ValidateSameSceneReferences(Scene scene,GameObject[] all){foreach(var b in all.SelectMany(g=>g.GetComponents<MonoBehaviour>()).Where(x=>x!=null)){var so=new SerializedObject(b);var p=so.GetIterator();while(p.NextVisible(true)){if(p.propertyType!=SerializedPropertyType.ObjectReference||p.objectReferenceValue==null)continue;if(p.objectReferenceValue is Component c&&c.gameObject.scene.IsValid()&&c.gameObject.scene!=scene)Error(scene.path+": cross-scene reference "+b.name+"."+p.propertyPath);if(p.objectReferenceValue is GameObject g&&g.scene.IsValid()&&g.scene!=scene)Error(scene.path+": cross-scene reference "+b.name+"."+p.propertyPath);}}}
    private static void ValidateButtons(GameObject[] all,string path,string[] names){foreach(string n in names){var buttons=all.Where(g=>g.name==n).SelectMany(g=>g.GetComponents<Button>()).ToArray();if(buttons.Length==0)Error(path+": missing button "+n);else if(buttons.All(b=>b.onClick.GetPersistentEventCount()==0))Error(path+": button not wired: "+n);}}
    private static void RequireText(GameObject[] all,string value,string path){if(!all.SelectMany(g=>g.GetComponents<TMPro.TMP_Text>()).Any(t=>t.text.Contains(value)))Error(path+": required Spanish/UI text missing: "+value);}
    private static void RequireRef(UnityEngine.Object target,string field,string path){if(target==null){Error(path+": missing target for reference "+field);return;}var p=new SerializedObject(target).FindProperty(field);if(p==null||p.objectReferenceValue==null)Error(path+": null serialized reference "+target.GetType().Name+"."+field);}
    private static void Need<T>(GameObject[] all,string path)where T:Component{if(!all.Any(g=>g.GetComponent<T>()!=null))Error(path+": missing "+typeof(T).Name);}
    private static void Exactly<T>(GameObject[] all,string path)where T:Component{int n=all.Sum(g=>g.GetComponents<T>().Length);if(n!=1)Error(path+$": expected exactly one {typeof(T).Name}, found {n}.");}
    private static void NeedAsset(string p){if(!System.IO.File.Exists(p)&&AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(p)==null)Error("Missing required asset: "+p);}
    private static void ValidateItem(string file,string id){var a=AssetDatabase.LoadAssetAtPath<InventoryItemDefinition>($"Assets/ScriptableObjects/Items/{file}.asset");if(a!=null&&a.Id!=id)Error($"{file}: expected ID {id}, got {a.Id}.");}
    private static void Error(string e)=>Errors.Add(e);
}
