using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using StarterAssets;
using TMPro;
using UnityEditor;
using UnityEditor.Events;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.UI;

public static class GuardianMistiGameBuilder
{
    private const string Root = "Assets";
    private static readonly Color Navy = new(0.025f, .07f, .12f, 1);
    private static readonly Color Cyan = new(.05f, .7f, .82f, 1);
    private static readonly Color Orange = new(1f, .42f, .08f, 1);
    private static Material floorMat, wallMat, accentMat, dangerMat, safeMat, rockMat, metalMat, emissiveMat, darkMat, vfxMat;
    private static InventoryItemDefinition backpack, radio, key;

    [MenuItem("Guardian Misti/Build Complete Game")]
    public static void BuildCompleteGame()
    {
        try
        {
            Debug.Log("[Guardian Misti] Preparing polished assets"); EnsureFolders(); CreateMaterials(); CreateVolumeProfiles(); CreateEarthquakeProfiles(); CreateAftershockProfile(); CreateItems(); CreatePrefabs();
            BuildMainMenu(); BuildLevel(false); BuildLevel(true);
            EditorBuildSettings.scenes = new[] {
                new EditorBuildSettingsScene("Assets/Scenes/MainMenu.unity", true),
                new EditorBuildSettingsScene("Assets/Scenes/Level01.unity", true),
                new EditorBuildSettingsScene("Assets/Scenes/Level02.unity", true)};
            AssetDatabase.SaveAssets(); AssetDatabase.Refresh();
            Debug.Log("GUARDIAN_MISTI_BUILD_SUCCESS");
        }
        catch (Exception ex) { Debug.LogException(ex); throw; }
    }

    [MenuItem("Guardian Misti/Build Linux Player")] public static void BuildLinuxPlayer(){Directory.CreateDirectory("Builds/Linux");var report=BuildPipeline.BuildPlayer(new[]{"Assets/Scenes/MainMenu.unity","Assets/Scenes/Level01.unity","Assets/Scenes/Level02.unity"},"Builds/Linux/GuardianMisti.x86_64",BuildTarget.StandaloneLinux64,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Linux build failed: "+report.summary.result);Debug.Log("GUARDIAN_MISTI_LINUX_BUILD_SUCCESS");}
    private static void EnsureFolders()
    {
        foreach (string path in new[]{"Assets/Editor","Assets/Scenes","Assets/Prefabs","Assets/Prefabs/Player","Assets/Prefabs/UI","Assets/Prefabs/Systems","Assets/Prefabs/Gameplay","Assets/ScriptableObjects","Assets/ScriptableObjects/Items","Assets/ScriptableObjects/Earthquakes","Assets/ScriptableObjects/Earthquake","Assets/Art/Materials","Assets/Materials","Assets/Settings/GuardianMisti","Assets/Prefabs/Environment","Assets/Prefabs/Props","Assets/Tests/EditMode"})
        {
            if (AssetDatabase.IsValidFolder(path)) continue;
            string parent=Path.GetDirectoryName(path).Replace('\\','/'); AssetDatabase.CreateFolder(parent, Path.GetFileName(path));
        }
    }

    private static void CreateMaterials()
    {
        floorMat=Mat("Assets/Art/Materials/GM_Floor.mat", new(.11f,.15f,.18f));
        wallMat=Mat("Assets/Art/Materials/GM_Wall.mat", new(.22f,.28f,.31f));
        accentMat=Mat("Assets/Art/Materials/GM_Accent.mat", Cyan);
        dangerMat=Mat("Assets/Art/Materials/GM_Danger.mat", Orange);
        safeMat=Mat("Assets/Art/Materials/GM_Safe.mat", new(.08f,.55f,.65f));
        rockMat=Mat("Assets/Materials/GM_VolcanicRock.mat",new(.09f,.075f,.065f));
        metalMat=Mat("Assets/Materials/GM_IndustrialMetal.mat",new(.18f,.21f,.22f));
        emissiveMat=Mat("Assets/Materials/GM_EmergencyEmissive.mat",new(1f,.18f,.04f),new(2.8f,.16f,.02f));
        darkMat=Mat("Assets/Materials/GM_DarkTrim.mat",new(.025f,.035f,.04f));
        vfxMat=ParticleMat("Assets/Materials/GM_DustParticle.mat");
    }
    private static Material Mat(string path, Color color, Color? emission=null)
    {
        var m=AssetDatabase.LoadAssetAtPath<Material>(path);
        if(m==null){ var shader=Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard"); m=new Material(shader); AssetDatabase.CreateAsset(m,path); }
        m.color=color; m.SetFloat("_Smoothness",path.Contains("Metal")?.65f:.25f); if(emission.HasValue){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",emission.Value);} EditorUtility.SetDirty(m); return m;
    }


    private static Material ParticleMat(string path){var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){var shader=Shader.Find("Universal Render Pipeline/Particles/Unlit");if(shader==null)throw new Exception("URP particle shader unavailable.");m=new Material(shader);AssetDatabase.CreateAsset(m,path);}m.color=new Color(.65f,.55f,.42f,.18f);EditorUtility.SetDirty(m);return m;}

    private static void CreateVolumeProfiles()
    {
        VolumeProfile("MainMenuVolume",.18f,-8f,new Color(.75f,.88f,1f),.22f);
        VolumeProfile("Level01Volume",.22f,-5f,new Color(1f,.82f,.72f),.18f);
        VolumeProfile("Level02Volume",.30f,-10f,new Color(.82f,.86f,1f),.24f);
    }
    private static VolumeProfile VolumeProfile(string name,float bloom,float temperature,Color filter,float vignette)
    {
        string path=$"Assets/Settings/GuardianMisti/{name}.asset";var profile=AssetDatabase.LoadAssetAtPath<VolumeProfile>(path);
        if(profile==null){profile=ScriptableObject.CreateInstance<VolumeProfile>();AssetDatabase.CreateAsset(profile,path);}
        foreach(var c in profile.components.ToArray())profile.Remove(c.GetType());
        var tone=profile.Add<Tonemapping>();tone.mode.Override(TonemappingMode.ACES);
        var color=profile.Add<ColorAdjustments>();color.postExposure.Override(.1f);color.contrast.Override(12f);color.colorFilter.Override(filter);
        var white=profile.Add<WhiteBalance>();white.temperature.Override(temperature);
        var b=profile.Add<Bloom>();b.intensity.Override(bloom);b.threshold.Override(1.1f);
        var v=profile.Add<Vignette>();v.intensity.Override(vignette);v.smoothness.Override(.45f);
        EditorUtility.SetDirty(profile);return profile;
    }

    private static void CreateEarthquakeProfiles()
    {
        EarthquakeAsset("Basic", "Básico", 16f, .045f, 115f);
        EarthquakeAsset("Intermediate", "Intermedio", 21f, .06f, 100f);
        EarthquakeAsset("Advanced", "Avanzado", 26f, .075f, 85f);
    }
    private static void EarthquakeAsset(string file,string display,float duration,float shake,float target)
    {
        string path="Assets/ScriptableObjects/Earthquakes/"+file+".asset";var p=AssetDatabase.LoadAssetAtPath<EarthquakeProfile>(path);if(p==null){p=ScriptableObject.CreateInstance<EarthquakeProfile>();AssetDatabase.CreateAsset(p,path);}
        var so=new SerializedObject(p);so.FindProperty("<DisplayName>k__BackingField").stringValue=display;so.FindProperty("<Duration>k__BackingField").floatValue=duration;so.FindProperty("<PreparationCountdown>k__BackingField").floatValue=3f;so.FindProperty("<CameraShakeIntensity>k__BackingField").floatValue=shake;so.FindProperty("<TargetSeconds>k__BackingField").floatValue=target;var curve=new AnimationCurve(new Keyframe(0,0),new Keyframe(.2f,.28f),new Keyframe(.48f,.82f),new Keyframe(.62f,1),new Keyframe(.82f,.48f),new Keyframe(1,0));foreach(string field in new[]{"<IntensityCurve>k__BackingField","<CameraShakeCurve>k__BackingField","<AudioVolumeCurve>k__BackingField","<LightFlickerCurve>k__BackingField","<DustEmissionCurve>k__BackingField","<PropForceCurve>k__BackingField"})so.FindProperty(field).animationCurveValue=curve;so.FindProperty("<MaximumPropForce>k__BackingField").floatValue=2.2f;so.FindProperty("<AudioIntensity>k__BackingField").floatValue=.72f;so.FindProperty("<LightFlickerIntensity>k__BackingField").floatValue=.24f;so.FindProperty("<MaximumDustEmission>k__BackingField").floatValue=6f;so.FindProperty("<MaximumActivePhysicsProps>k__BackingField").intValue=5;so.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void CreateAftershockProfile(){string path="Assets/ScriptableObjects/Earthquake/Level02AftershockProfile.asset";if(AssetDatabase.LoadAssetAtPath<EarthquakeProfile>(path)==null)AssetDatabase.CopyAsset("Assets/ScriptableObjects/Earthquakes/Basic.asset",path);}

    private static void CreateItems()
    {
        Sprite icon=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/Icons/backpack.png");
        backpack=Item("EmergencyBackpack",GameIds.EmergencyBackpack,"Mochila de emergencia","Suministros esenciales para evacuar.",icon);
        radio=Item("EmergencyRadio",GameIds.EmergencyRadio,"Radio de emergencia","Radio portátil para pedir ayuda.",icon);
        key=Item("AccessKey",GameIds.AccessKey,"Llave de acceso","Abre el control de la baliza.",icon);
    }
    private static InventoryItemDefinition Item(string file,string id,string name,string desc,Sprite icon)
    {
        string path=$"Assets/ScriptableObjects/Items/{file}.asset";
        var item=AssetDatabase.LoadAssetAtPath<InventoryItemDefinition>(path);
        if(item==null){item=ScriptableObject.CreateInstance<InventoryItemDefinition>();AssetDatabase.CreateAsset(item,path);}
        Set(item,"<Id>k__BackingField",id);Set(item,"<Name>k__BackingField",name);Set(item,"<Description>k__BackingField",desc);Set(item,"<Icon>k__BackingField",icon);return item;
    }

    private static void CreatePrefabs()
    {
        SavePrefab(PlayerObject(),"Assets/Prefabs/Player/GameplayPlayer.prefab");
        SavePrefab(HudObject(),"Assets/Prefabs/UI/GameplayHUD.prefab");
        var systems=new GameObject("GameplaySystems"); systems.AddComponent<SceneLoader>(); systems.AddComponent<GameplayCursorController>(); SavePrefab(systems,"Assets/Prefabs/Systems/GameplaySystems.prefab");
        var door=ComposedDoor("FacilityExitDoor",Vector3.zero);var doorController=door.AddComponent<DoorController>();Set(doorController,"doorLeaf",Find(door.transform,"DoorLeaf"));Set(doorController,"blockingCollider",door.GetComponent<Collider>());SavePrefab(door,"Assets/Prefabs/Gameplay/FacilityExitDoor.prefab");
        var collectible=BackpackModel("CollectibleItem",Vector3.zero);collectible.AddComponent<CollectibleItemController>();SavePrefab(collectible,"Assets/Prefabs/Gameplay/CollectibleItem.prefab");
        var exit=TriggerMarker("LevelExit",Vector3.zero,new Vector3(3,2,.3f));Sign("ExitVisual",new Vector3(0,1,0),safeMat).transform.SetParent(exit.transform);exit.AddComponent<LevelExitController>();SavePrefab(exit,"Assets/Prefabs/Gameplay/LevelExit.prefab");
        var zone=TriggerMarker("SafeZone",Vector3.zero,new Vector3(5,2,5));SafeZoneVisual(zone.transform,new Vector3(0,-1,0));zone.AddComponent<SafeZoneController>();SavePrefab(zone,"Assets/Prefabs/Gameplay/SafeZone.prefab");
        SavePrefab(TerminalModel("EvacuationTerminal",Vector3.zero),"Assets/Prefabs/Gameplay/EvacuationTerminal.prefab");
        SavePrefab(BeaconModel("EmergencyBeacon",Vector3.zero),"Assets/Prefabs/Gameplay/EmergencyBeacon.prefab");
        SavePrefab(BackpackModel("EmergencyBackpack",Vector3.zero),"Assets/Prefabs/Gameplay/EmergencyBackpack.prefab");
        SavePrefab(InteriorProtectionZoneModel(),"Assets/Prefabs/Gameplay/InteriorProtectionZone.prefab");
        SavePrefab(RadioModel("EmergencyRadio",Vector3.zero),"Assets/Prefabs/Gameplay/EmergencyRadio.prefab");SavePrefab(KeyModel("AccessKey",Vector3.zero),"Assets/Prefabs/Gameplay/AccessKey.prefab");
        var shelter=Imported("Assets/StarterAssets/Environment/Prefabs/Structure_Prefab.prefab",null,Vector3.zero,Vector3.one);shelter.name="FacilityModule";SavePrefab(shelter,"Assets/Prefabs/Environment/FacilityModule.prefab");
        SavePrefab(ExternalWrapper("KenneyDesk","Assets/ThirdParty/Kenney/FurnitureKit/Models/desk.fbx",Vector3.one*.25f,metalMat,new Vector3(2.1f,1.1f,1.1f)),"Assets/Prefabs/Environment/KenneyDesk.prefab");SavePrefab(ExternalWrapper("KenneyChair","Assets/ThirdParty/Kenney/FurnitureKit/Models/chairDesk.fbx",Vector3.one*.25f,accentMat,new Vector3(.8f,1.2f,.8f)),"Assets/Prefabs/Environment/KenneyChair.prefab");SavePrefab(ExternalWrapper("KenneyShelf","Assets/ThirdParty/Kenney/FurnitureKit/Models/bookcaseOpen.fbx",Vector3.one*.25f,metalMat,new Vector3(1.4f,2.2f,.45f)),"Assets/Prefabs/Environment/KenneyShelf.prefab");SavePrefab(ExternalWrapper("KenneyDoorFrame","Assets/ThirdParty/Kenney/FurnitureKit/Models/doorway.fbx",Vector3.one*.25f,wallMat,new Vector3(2.6f,2.8f,.3f)),"Assets/Prefabs/Environment/KenneyDoorFrame.prefab");SavePrefab(ExternalWrapper("KenneyRock","Assets/ThirdParty/Kenney/SurvivalKit/Models/rock-a.fbx",Vector3.one*.1f,rockMat,new Vector3(1.2f,.8f,1.2f)),"Assets/Prefabs/Environment/KenneyRock.prefab");SavePrefab(ExternalWrapper("KenneySignpost","Assets/ThirdParty/Kenney/SurvivalKit/Models/signpost.fbx",Vector3.one*.1f,safeMat,new Vector3(.5f,2,.5f)),"Assets/Prefabs/Environment/KenneySignpost.prefab");SavePrefab(ExternalWrapper("KenneyRescueTent","Assets/ThirdParty/Kenney/SurvivalKit/Models/tent-canvas.fbx",Vector3.one*.1f,safeMat,new Vector3(3,2,3)),"Assets/Prefabs/Environment/KenneyRescueTent.prefab");
        SavePrefab(ExternalWrapper("Desk","Assets/ThirdParty/Kenney/FurnitureKit/Models/desk.fbx",Vector3.one*.25f,metalMat,new Vector3(2.1f,1.1f,1.1f)),"Assets/Prefabs/Environment/Desk.prefab");SavePrefab(ExternalWrapper("Chair","Assets/ThirdParty/Kenney/FurnitureKit/Models/chairDesk.fbx",Vector3.one*.25f,accentMat,new Vector3(.8f,1.2f,.8f)),"Assets/Prefabs/Environment/Chair.prefab");SavePrefab(ExternalWrapper("Shelf","Assets/ThirdParty/Kenney/FurnitureKit/Models/bookcaseOpen.fbx",Vector3.one*.25f,metalMat,new Vector3(1.4f,2.2f,.45f)),"Assets/Prefabs/Environment/Shelf.prefab");SavePrefab(EmergencySignModel("EmergencySign",Vector3.zero),"Assets/Prefabs/Environment/EmergencySign.prefab");
    }
    private static void SavePrefab(GameObject go,string path){PrefabUtility.SaveAsPrefabAsset(go,path);UnityEngine.Object.DestroyImmediate(go);}

    private static GameObject PlayerObject()
    {
        var player=new GameObject("GameplayPlayer");player.tag="Player";var cc=player.AddComponent<CharacterController>();cc.center=new Vector3(0,1,0);cc.height=2f;cc.radius=.38f;cc.skinWidth=.08f;cc.stepOffset=.32f;cc.slopeLimit=48f;cc.minMoveDistance=0f;
        var inputs=player.AddComponent<StarterAssetsInputs>(); var pi=player.AddComponent<PlayerInput>();
        pi.actions=AssetDatabase.LoadAssetAtPath<InputActionAsset>("Assets/InputSystem_Actions.inputactions");pi.defaultActionMap="Player";pi.notificationBehavior=PlayerNotifications.SendMessages;
        var target=new GameObject("CameraRoot");target.transform.SetParent(player.transform);target.transform.localPosition=new Vector3(0,1.65f,0);
        var camGo=new GameObject("Main Camera");camGo.tag="MainCamera";camGo.transform.SetParent(target.transform);camGo.transform.localPosition=Vector3.zero;var cam=camGo.AddComponent<Camera>();cam.fieldOfView=72f;cam.nearClipPlane=.08f;cam.farClipPlane=350f;camGo.AddComponent<AudioListener>();
        player.layer=2;var fpc=player.AddComponent<FirstPersonController>();fpc.CinemachineCameraTarget=target;fpc.GroundLayers=1<<0;fpc.GroundedOffset=.14f;fpc.GroundedRadius=.28f;fpc.JumpHeight=1.05f;fpc.Gravity=-18f;fpc.JumpTimeout=.15f;fpc.FallTimeout=.12f;var jumpGate=player.AddComponent<JumpInputGate>();Set(jumpGate,"inputs",inputs);
        var interaction=player.AddComponent<InteractionSystem>();var crouch=player.AddComponent<PlayerCrouchController>();Set(crouch,"characterController",cc);Set(crouch,"movement",fpc);Set(crouch,"inputs",inputs);Set(crouch,"playerInput",pi);Set(crouch,"cameraHeightRoot",target.transform);var state=player.AddComponent<GameplayStateController>();Set(state,"playerInput",pi);Set(state,"movement",fpc);Set(state,"starterInputs",inputs);Set(state,"interaction",interaction);Set(state,"crouch",crouch); return player;
    }

    private static GameObject HudObject()
    {
        return BuildGameplayHud(out _,out _,out _,out _,out _,out _,out _,out _).gameObject;
    }

    private static void BuildMainMenu()
    {
        PrepareScene("Assets/Scenes/MainMenu.unity"); var generated=new GameObject("Generated_GuardianMisti"); var cam=new GameObject("Main Camera");cam.transform.SetParent(generated.transform);cam.transform.position=new Vector3(0,4,-14);cam.transform.rotation=Quaternion.Euler(8,0,0);cam.tag="MainCamera";var menuCam=cam.AddComponent<Camera>();menuCam.backgroundColor=Navy;menuCam.fieldOfView=58;cam.AddComponent<AudioListener>();AddVolume(generated.transform,"MainMenuVolume");CreateMenuBackdrop(generated.transform);
        EventSystem(); var app=new GameObject("App");var loader=app.AddComponent<SceneLoader>();var menu=app.AddComponent<MainMenuController>();Set(menu,"sceneLoader",loader);
        var canvas=CanvasRoot("Canvas");ImageObj("Background",canvas.transform,new Vector2(.5f,.5f),new Vector2(1920,1080),Navy);var menuCard=Panel("MenuCard",canvas.transform,new Vector2(.5f,.5f),new Vector2(760,820));menuCard.GetComponent<Image>().color=new Color(.02f,.055f,.08f,.96f);Text("Eyebrow",menuCard.transform,"SIMULACIÓN EDUCATIVA DE EMERGENCIA",14,new Vector2(.5f,.89f),new Vector2(650,28),Cyan,FontStyles.Bold);Text("Title",menuCard.transform,"GUARDIAN MISTI",54,new Vector2(.5f,.78f),new Vector2(650,90),Color.white,FontStyles.Bold);Text("Subtitle",menuCard.transform,"Preparación, evacuación y respuesta",22,new Vector2(.5f,.69f),new Vector2(620,50),new(.65f,.78f,.82f));ButtonObj("PlayButton",menuCard.transform,"INICIAR SIMULACIÓN",new Vector2(.5f,.52f),menu.StartGame);ButtonObj("InstructionsButton",menuCard.transform,"INSTRUCCIONES",new Vector2(.5f,.40f),menu.ToggleInstructions);ButtonObj("ExitButton",menuCard.transform,"SALIR",new Vector2(.5f,.28f),menu.QuitGame);var instructions=Text("Instructions",menuCard.transform,"WASD: Movimiento  •  Mouse: Mirar  •  E: Interactuar\nCtrl izquierdo: Agacharse  •  Espacio: Saltar  •  Esc: Pausa  •  F3: Diagnóstico",17,new Vector2(.5f,.13f),new Vector2(650,70),Color.white);Set(menu,"instructionsPanel",instructions.gameObject);instructions.gameObject.SetActive(false); ConsolidateGenerated(generated);
        SaveScene("Assets/Scenes/MainMenu.unity");
    }

    private static void BuildLevel(bool level2)
    {
        string sceneName=level2?"Level02":"Level01";PrepareScene($"Assets/Scenes/{sceneName}.unity");var generated=new GameObject("Generated_GuardianMisti");
        RenderSettings.ambientLight=level2?new Color(.22f,.24f,.27f):new Color(.30f,.28f,.26f);RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.fog=true;RenderSettings.fogColor=level2?new Color(.28f,.25f,.22f):new Color(.16f,.17f,.18f);RenderSettings.fogDensity=level2?.012f:.006f;
        var light=new GameObject("Directional Light");light.transform.SetParent(generated.transform);var dl=light.AddComponent<Light>();dl.type=LightType.Directional;dl.intensity=level2?1.05f:1.2f;dl.shadows=LightShadows.Soft;light.transform.rotation=Quaternion.Euler(48,-28,0);
        AddVolume(generated.transform,level2?"Level02Volume":"Level01Volume");
        if (level2) BuildEnvironment(generated.transform, true); else BuildLevel01Interior(generated.transform);
        var app=new GameObject("App");var sceneLoader=app.AddComponent<SceneLoader>();if(!level2){var sessionRoot=new GameObject("SimulationSession");sessionRoot.AddComponent<SimulationSession>();sessionRoot.AddComponent<SimulationResearchRecorder>();}new GameObject("GameplayCursorController").AddComponent<GameplayCursorController>();
        EventSystem(); var player=PlayerObject();player.transform.position=new Vector3(0,.08f,0);player.AddComponent<SimulationMetricsProbe>();var fpc=player.GetComponent<FirstPersonController>();var interaction=player.GetComponent<InteractionSystem>();var inputs=player.GetComponent<StarterAssetsInputs>();var camera=player.GetComponentInChildren<Camera>();
        var canvas=BuildGameplayHud(out var objectiveUI,out var inventoryUI,out var notificationUI,out var interactionUI,out var pausePanel,out var completionPanel,out var completionUI,out var completionController);
        Set(interaction,"playerCamera",camera);Set(interaction,"interactionUIController",interactionUI);var crouch=player.GetComponent<PlayerCrouchController>();Set(crouch,"crouchStatus",Find(canvas.transform,"CrouchStatus").GetComponent<TextMeshProUGUI>());
        var managers=new GameObject("GameplaySystems");var inventory=managers.AddComponent<InventoryManager>();Set(inventory,"inventoryUI",inventoryUI);Set(inventory,"notificationUI",notificationUI);
        var objectives=managers.AddComponent<ObjectivesManager>();Set(objectives,"objectiveUI",objectiveUI);SetObjectives(objectives,level2);
        EarthquakeController quake=null;if(!level2){var quakeDust=Dust(new Vector3(0,2,8),new Vector3(10,2.5f,16),25);quakeDust.name="EarthquakeDust";var quakeDebris=EarthquakeDebris(new Vector3(0,3.55f,2));var props=BuildEarthquakeProps();var rumble=EarthquakeAudio(managers,"EarthquakeRumble",true);var alarm=EarthquakeAudio(managers,"EarthquakeAlarm",true);var impacts=EarthquakeAudio(managers,"EarthquakeImpacts",false);var allLights=UnityEngine.Object.FindObjectsByType<Light>(FindObjectsInactive.Include);foreach(var emergency in allLights.Where(l=>l.name=="EmergencyLight"))emergency.enabled=false;quake=managers.AddComponent<EarthquakeController>();Set(quake,"profile",AssetDatabase.LoadAssetAtPath<EarthquakeProfile>("Assets/ScriptableObjects/Earthquakes/Intermediate.asset"));Set(quake,"cameraEffectRoot",camera.transform);SetArray(quake,"stableLights",allLights.Where(l=>l.name=="CeilingLightFixture"||l.name=="Directional Light").ToArray());SetArray(quake,"emergencyLights",allLights.Where(l=>l.name=="EmergencyLight").ToArray());Set(quake,"dust",quakeDust);Set(quake,"debris",quakeDebris);Set(quake,"rumbleSource",rumble);Set(quake,"alarmSource",alarm);Set(quake,"impactSource",impacts);SetArray(quake,"reactiveProps",props);Set(quake,"objectivesManager",objectives);var quakeUI=canvas.gameObject.AddComponent<EarthquakeUIController>();Set(quakeUI,"earthquakeController",quake);Set(quakeUI,"countdownText",Find(canvas.transform,"EarthquakeCountdown").GetComponent<TextMeshProUGUI>());Set(quakeUI,"intensityText",Find(canvas.transform,"EarthquakeIntensity").GetComponent<TextMeshProUGUI>());}
        var stateController=player.GetComponent<GameplayStateController>();Set(stateController,"pausePanel",pausePanel);Set(stateController,"completionPanel",completionPanel);Set(sceneLoader,"stateController",stateController);var runtimeLogger=player.AddComponent<GameplayRuntimeLogger>();Set(runtimeLogger,"stateController",stateController);Set(runtimeLogger,"inputs",inputs);Set(runtimeLogger,"playerInput",player.GetComponent<PlayerInput>());Set(runtimeLogger,"movement",fpc);Set(runtimeLogger,"characterController",player.GetComponent<CharacterController>());var diagnostics=player.AddComponent<GameplayDiagnostics>();Set(diagnostics,"stateController",stateController);Set(diagnostics,"playerInput",player.GetComponent<PlayerInput>());Set(diagnostics,"inputs",inputs);Set(diagnostics,"movement",fpc);Set(diagnostics,"characterController",player.GetComponent<CharacterController>());Set(diagnostics,"interaction",interaction);Set(diagnostics,"pausePanel",pausePanel);Set(diagnostics,"completionPanel",completionPanel);Set(diagnostics,"runtimeLogger",runtimeLogger);var overlay=canvas.gameObject.AddComponent<GameplayDiagnosticsOverlay>();Set(overlay,"diagnostics",diagnostics);Set(overlay,"panel",Find(canvas.transform,"DiagnosticsPanel").gameObject);Set(overlay,"diagnosticText",Find(canvas.transform,"DiagnosticsText").GetComponent<TextMeshProUGUI>());var pause=managers.AddComponent<PauseController>();Set(pause,"sceneLoader",sceneLoader);Set(pause,"stateController",stateController);
        Set(completionController,"sceneLoader",sceneLoader);Set(completionController,"stateController",stateController);Set(completionController,"pauseController",pause);
        WirePauseButtons(pausePanel,pause);WireCompletionButtons(completionPanel,completionController);AddSettings(Find(pausePanel.transform,"PauseCard").gameObject,fpc);
        if(level2) PopulateLevel02(objectives,inventory,notificationUI,completionUI); else PopulateLevel01(objectives,inventory,notificationUI,sceneLoader,quake);
        pausePanel.SetActive(false);completionPanel.SetActive(false);ConsolidateGenerated(generated);SaveScene($"Assets/Scenes/{sceneName}.unity");
    }

    private static Canvas BuildGameplayHud(out ObjectiveUI objectiveUI,out InventoryUI inventoryUI,out NotificationUI notificationUI,out InteractionUIController interactionUI,out GameObject pause,out GameObject completion,out GameCompletionUI completionUI,out GameCompletionController completionController)
    {
        var canvas=CanvasRoot("GameplayHUD");var hud=Rect("HUD",canvas.transform,Vector2.zero,Vector2.one);
        var crossImage=ImageObj("Crosshair",hud.transform,new Vector2(.5f,.5f),new Vector2(9,9),Color.white);crossImage.GetComponent<Image>().raycastTarget=false;var cross=crossImage.AddComponent<CrosshairUI>();Set(cross,"crossHair",crossImage.GetComponent<Image>());
        var prompt=Panel("InteractionPrompt",hud.transform,new Vector2(.5f,.32f),new Vector2(620,58));prompt.GetComponent<Image>().raycastTarget=false;var promptText=Text("PromptText",prompt.transform,"",21,new Vector2(.5f,.5f),new Vector2(590,48),Color.white,FontStyles.Bold);promptText.raycastTarget=false;var promptUI=prompt.AddComponent<InteractionPromptUI>();Set(promptUI,"promptText",promptText);
        var op=Panel("ObjectivePanel",hud.transform,new Vector2(.22f,.91f),new Vector2(680,100));op.GetComponent<Image>().raycastTarget=false;Text("Label",op.transform,"OBJETIVO ACTUAL",14,new Vector2(.5f,.73f),new Vector2(630,24),Cyan,FontStyles.Bold).raycastTarget=false;var ot=Text("ObjectiveText",op.transform,"",21,new Vector2(.5f,.35f),new Vector2(630,48),Color.white);ot.enableWordWrapping=true;ot.raycastTarget=false;objectiveUI=op.AddComponent<ObjectiveUI>();Set(objectiveUI,"objectiveText",ot);var objectiveGroup=op.AddComponent<CanvasGroup>();objectiveGroup.blocksRaycasts=false;Set(objectiveUI,"canvasGroup",objectiveGroup);
        var protectionHint=Text("ProtectionObjectiveHint",hud.transform,"",16,new Vector2(.22f,.845f),new Vector2(620,34),new Color(.72f,.92f,.96f),FontStyles.Italic);protectionHint.raycastTarget=false;protectionHint.gameObject.SetActive(false);
        var crouchStatus=Text("CrouchStatus",hud.transform,"AGACHADO",15,new Vector2(.91f,.18f),new Vector2(180,36),Cyan,FontStyles.Bold);crouchStatus.raycastTarget=false;crouchStatus.gameObject.SetActive(false);
        var dwellProgress=Text("ProtectionDwellProgress",hud.transform,"",15,new Vector2(.5f,.43f),new Vector2(320,34),Cyan,FontStyles.Bold);dwellProgress.raycastTarget=false;dwellProgress.gameObject.SetActive(false);
        var aftershockWarning=Text("AftershockWarning",hud.transform,"",17,new Vector2(.5f,.76f),new Vector2(700,74),Orange,FontStyles.Bold);aftershockWarning.lineSpacing=18;aftershockWarning.raycastTarget=false;aftershockWarning.gameObject.SetActive(false);
        var protectionPrompt=Text("ProtectionContextPrompt",hud.transform,"",18,new Vector2(.5f,.39f),new Vector2(520,42),Color.white,FontStyles.Bold);protectionPrompt.raycastTarget=false;protectionPrompt.gameObject.SetActive(false);
        var timerPanel=Panel("TimerPanel",hud.transform,new Vector2(.5f,.93f),new Vector2(260,70));timerPanel.GetComponent<Image>().raycastTarget=false;Text("TimerLabel",timerPanel.transform,"TIEMPO",12,new Vector2(.5f,.76f),new Vector2(230,18),Cyan,FontStyles.Bold).raycastTarget=false;var timerText=Text("TimerText",timerPanel.transform,"00:00.000",25,new Vector2(.5f,.38f),new Vector2(230,38),Color.white,FontStyles.Bold);timerText.raycastTarget=false;var simHud=timerPanel.AddComponent<SimulationHud>();Set(simHud,"timerText",timerText);
        var intensityPanel=Panel("EarthquakeIntensityPanel",hud.transform,new Vector2(.5f,.84f),new Vector2(360,66));intensityPanel.GetComponent<Image>().raycastTarget=false;Text("IntensityLabel",intensityPanel.transform,"INTENSIDAD SIMULADA",12,new Vector2(.5f,.72f),new Vector2(330,20),Orange,FontStyles.Bold).raycastTarget=false;var intensity=Text("EarthquakeIntensity",intensityPanel.transform,"",18,new Vector2(.5f,.3f),new Vector2(330,28),Color.white,FontStyles.Bold);intensity.raycastTarget=false;var countdown=Text("EarthquakeCountdown",hud.transform,"",34,new Vector2(.5f,.66f),new Vector2(900,80),Color.white,FontStyles.Bold);countdown.alignment=TextAlignmentOptions.Center;countdown.raycastTarget=false;countdown.gameObject.SetActive(false);intensityPanel.SetActive(false);
        var ip=Panel("InventoryPanel",hud.transform,new Vector2(.82f,.91f),new Vector2(570,108));ip.GetComponent<Image>().raycastTarget=false;Text("InventoryLabel",ip.transform,"EQUIPO",12,new Vector2(.08f,.82f),new Vector2(80,20),Cyan,FontStyles.Bold).raycastTarget=false;var slots=new[]{InventorySlot(ip.transform,"BackpackSlot",GameIds.EmergencyBackpack,"MOCHILA","Assets/Art/Icons/backpack.png",.25f),InventorySlot(ip.transform,"RadioSlot",GameIds.EmergencyRadio,"RADIO","Assets/Modern UI Pack/Textures/Icon/Device/Phone.png",.53f),InventorySlot(ip.transform,"AccessKeySlot",GameIds.AccessKey,"ACCESO","Assets/Modern UI Pack/Textures/Icon/Commerce/Card.png",.81f)};inventoryUI=ip.AddComponent<InventoryUI>();SetArray(inventoryUI,"slots",slots);
        var diagnosticsPanel=Panel("DiagnosticsPanel",canvas.transform,new Vector2(.18f,.55f),new Vector2(650,760));var diagnosticsGroup=diagnosticsPanel.AddComponent<CanvasGroup>();diagnosticsGroup.interactable=false;diagnosticsGroup.blocksRaycasts=false;var diagnosticsText=Text("DiagnosticsText",diagnosticsPanel.transform,"F3 DIAGNÓSTICOS",14,new Vector2(.5f,.5f),new Vector2(620,730),Color.white);diagnosticsText.alignment=TextAlignmentOptions.TopLeft;diagnosticsPanel.SetActive(false);
        var notifications=Rect("Notifications",canvas.transform,Vector2.zero,Vector2.one);var np=Panel("NotificationPanel",notifications.transform,new Vector2(.5f,.77f),new Vector2(560,94));var ni=ImageObj("Icon",np.transform,new Vector2(.11f,.5f),new Vector2(58,58),new Color(.15f,.85f,1));var nt=Text("Title",np.transform,"",16,new Vector2(.58f,.68f),new Vector2(420,28),Cyan,FontStyles.Bold);var nd=Text("Description",np.transform,"",18,new Vector2(.58f,.34f),new Vector2(420,34),Color.white);notificationUI=np.AddComponent<NotificationUI>();Set(notificationUI,"icon",ni.GetComponent<Image>());Set(notificationUI,"titleText",nt);Set(notificationUI,"descriptionText",nd);np.SetActive(false);
        var screens=Rect("Screens",canvas.transform,Vector2.zero,Vector2.one);pause=FullPanel("PausePanel",screens.transform,"SIMULACIÓN EN PAUSA");var pauseCard=Panel("PauseCard",pause.transform,new Vector2(.5f,.48f),new Vector2(760,730));pauseCard.GetComponent<Image>().color=new Color(.025f,.065f,.09f,.98f);Text("SettingsHeader",pauseCard.transform,"CONFIGURACIÓN",15,new Vector2(.5f,.42f),new Vector2(640,30),Cyan,FontStyles.Bold);ButtonObj("ResumeButton",pauseCard.transform,"CONTINUAR",new Vector2(.5f,.82f),null);ButtonObj("RestartButton",pauseCard.transform,"REINICIAR NIVEL",new Vector2(.5f,.69f),null);ButtonObj("MenuButton",pauseCard.transform,"VOLVER AL MENÚ",new Vector2(.5f,.56f),null);
        completion=FullPanel("CompletionPanel",screens.transform,"MISIÓN COMPLETADA");var resultCard=Panel("ResultsCard",completion.transform,new Vector2(.5f,.51f),new Vector2(1160,720));resultCard.GetComponent<Image>().color=new Color(.025f,.065f,.09f,.98f);Text("SummaryHeader",resultCard.transform,"RESUMEN",14,new Vector2(.5f,.92f),new Vector2(1000,24),Cyan,FontStyles.Bold);var total=ResultMetric(resultCard.transform,"TotalTime","TIEMPO TOTAL",.23f,.81f,25);var score=ResultMetric(resultCard.transform,"Score","PUNTAJE FINAL",.5f,.81f,34);var grade=ResultMetric(resultCard.transform,"Grade","CALIFICACIÓN",.77f,.81f,25);Text("BreakdownHeader",resultCard.transform,"DESGLOSE POR NIVEL",14,new Vector2(.27f,.61f),new Vector2(440,24),Cyan,FontStyles.Bold);var l1=ResultRow(resultCard.transform,"Level01","TIEMPO NIVEL 1",.24f,.52f);var l2=ResultRow(resultCard.transform,"Level02","TIEMPO NIVEL 2",.24f,.43f);Text("PerformanceHeader",resultCard.transform,"RENDIMIENTO",14,new Vector2(.73f,.61f),new Vector2(440,24),Cyan,FontStyles.Bold);var incorrect=ResultRow(resultCard.transform,"Incorrect","INTERACCIONES INCORRECTAS",.73f,.52f);var hazards=ResultRow(resultCard.transform,"Hazards","RIESGOS ENCONTRADOS",.73f,.43f);var pauses=ResultRow(resultCard.transform,"Pauses","PAUSAS",.73f,.34f);var best=ResultRow(resultCard.transform,"BestTime","MEJOR TIEMPO",.24f,.34f);var results=resultCard.AddComponent<SimulationResultsUI>();Set(results,"totalTimeValue",total);Set(results,"scoreValue",score);Set(results,"gradeValue",grade);Set(results,"level01Value",l1);Set(results,"level02Value",l2);Set(results,"incorrectValue",incorrect);Set(results,"hazardsValue",hazards);Set(results,"pausesValue",pauses);Set(results,"bestTimeValue",best);ButtonAt("RestartButton",completion.transform,"REINICIAR SIMULACIÓN",new Vector2(.27f,.11f),null);ButtonAt("MenuButton",completion.transform,"VOLVER AL MENÚ",new Vector2(.5f,.11f),null);ButtonAt("ExitButton",completion.transform,"SALIR",new Vector2(.73f,.11f),null);completionController=completion.AddComponent<GameCompletionController>();completionUI=completion.AddComponent<GameCompletionUI>();Set(completionUI,"controller",completionController);
        interactionUI=canvas.gameObject.AddComponent<InteractionUIController>();Set(interactionUI,"promptUI",promptUI);Set(interactionUI,"crosshairUI",cross);prompt.SetActive(false);return canvas;
    }

    private static void PopulateLevel01(ObjectivesManager om,InventoryManager im,NotificationUI note,SceneLoader loader,EarthquakeController quake)
    {
        var protection=PrefabInstance("Assets/Prefabs/Gameplay/InteriorProtectionZone.prefab",null,new Vector3(-3.2f,0,1.35f),Vector3.one,"Generated_InteriorProtectionZone");
        var protectionController=protection.GetComponentInChildren<EarthquakeProtectionTrigger>(true);Set(protectionController,"earthquakeController",quake);Set(protectionController,"objectivesManager",om);Set(protectionController,"notificationUI",note);Set(protectionController,"crouchController",UnityEngine.Object.FindFirstObjectByType<PlayerCrouchController>());Set(protectionController,"dwellProgressText",UnityEngine.Object.FindObjectsByType<TMP_Text>(FindObjectsInactive.Include).First(t=>t.name=="ProtectionDwellProgress"));
        var player=UnityEngine.Object.FindFirstObjectByType<FirstPersonController>().transform;Set(protectionController,"player",player);Set(protectionController,"playerCamera",player.GetComponentInChildren<Camera>());Set(protectionController,"contextualPrompt",UnityEngine.Object.FindObjectsByType<TMP_Text>(FindObjectsInactive.Include).First(t=>t.name=="ProtectionContextPrompt"));Set(protectionController,"objectiveHint",UnityEngine.Object.FindObjectsByType<TMP_Text>(FindObjectsInactive.Include).First(t=>t.name=="ProtectionObjectiveHint"));Set(quake,"notificationUI",note);
        var door=PrefabInstance("Assets/Prefabs/Gameplay/FacilityExitDoor.prefab",null,new Vector3(0,1.47f,5),Vector3.one,"InitialDoor");var dc=door.GetComponent<DoorController>();Set(dc,"objectiveId",GameIds.Level01ExitRoom);Set(dc,"earthquakeController",quake);Set(dc,"objectivesManager",om);
        var item=PrefabInstance("Assets/Prefabs/Gameplay/EmergencyBackpack.prefab",null,new Vector3(-1.75f,1.02f,8.15f),Vector3.one,"EmergencyBackpack");var cc=item.AddComponent<CollectibleItemController>();Set(cc,"definition",backpack);Set(cc,"objectiveId",GameIds.Level01CollectBackpack);
        var terminal=PrefabInstance("Assets/Prefabs/Gameplay/EvacuationTerminal.prefab",null,new Vector3(2.35f,0,12.2f),Vector3.one,"EvacuationTerminal");terminal.transform.rotation=Quaternion.Euler(0,90,0);var tc=terminal.AddComponent<EvacuationTerminalController>();Set(tc,"notificationUI",note);Set(tc,"statusRenderer",Find(terminal.transform,"StatusLight").GetComponent<Renderer>());
        var exit=TriggerMarker("LevelExit",new Vector3(0,1,19.2f),new Vector3(4.8f,2,.6f));var ec=exit.AddComponent<LevelExitController>();Set(ec,"sceneLoader",loader);Set(ec,"objectivesManager",om);Set(ec,"objectiveId",GameIds.Level01ReachExit);
        FacilitySign("LevelExitSign","SALIDA · RUTA DE EVACUACIÓN",new Vector3(0,2.85f,18.65f),new Vector3(4.5f,.72f,.08f),safeMat);
    }
    private static void PopulateLevel02(ObjectivesManager om,InventoryManager im,NotificationUI note,GameCompletionUI completion)
    {
        BuildLevel02Aftershock();
        var r=PrefabInstance("Assets/Prefabs/Gameplay/EmergencyRadio.prefab",null,new Vector3(-3,.65f,5),Vector3.one,"EmergencyRadio");var rc=r.AddComponent<CollectibleItemController>();Set(rc,"definition",radio);Set(rc,"objectiveId",GameIds.Level02CollectRadio);
        var k=PrefabInstance("Assets/Prefabs/Gameplay/AccessKey.prefab",null,new Vector3(3,.75f,9),Vector3.one,"AccessKey");var kc=k.AddComponent<CollectibleItemController>();Set(kc,"definition",key);Set(kc,"objectiveId",GameIds.Level02CollectAccessKey);
        var b=PrefabInstance("Assets/Prefabs/Gameplay/EmergencyBeacon.prefab",null,new Vector3(0,0,13),Vector3.one,"EmergencyBeacon");var bc=b.AddComponent<EmergencyBeaconController>();Set(bc,"notificationUI",note);Set(bc,"statusRenderer",Find(b.transform,"StatusLight").GetComponent<Renderer>());
        var z=PrefabInstance("Assets/Prefabs/Gameplay/SafeZone.prefab",null,new Vector3(0,1,19),new Vector3(1.4f,1,1),"SafeZone");var sc=z.GetComponent<SafeZoneController>();Set(sc,"objectivesManager",om);Set(sc,"completionUI",completion);Dust(new Vector3(0,2,11),new Vector3(14,5,25),55);
    }

    private static void BuildLevel02Aftershock(){var systems=UnityEngine.Object.FindFirstObjectByType<ObjectivesManager>().gameObject;var controller=systems.AddComponent<AftershockController>();Set(controller,"profile",AssetDatabase.LoadAssetAtPath<EarthquakeProfile>("Assets/ScriptableObjects/Earthquake/Level02AftershockProfile.asset"));var player=UnityEngine.Object.FindFirstObjectByType<FirstPersonController>().transform;Set(controller,"player",player);Set(controller,"cameraEffectRoot",player.GetComponentInChildren<Camera>().transform);Set(controller,"stableFloor",UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsInactive.Include).First(t=>t.name=="Collision_Ground"));Set(controller,"warningText",UnityEngine.Object.FindObjectsByType<TMP_Text>(FindObjectsInactive.Include).First(t=>t.name=="AftershockWarning"));var dust=Dust(new Vector3(-6,2,10),new Vector3(3,4,12),30);dust.name="AftershockDust";Set(controller,"dust",dust);var props=new List<EarthquakeReactiveProp>();foreach(var spec in new[]{(new Vector3(-6,.6f,7),new Vector3(.7f,.7f,.7f)),(new Vector3(6,.6f,11),new Vector3(.8f,.8f,.8f)),(new Vector3(-6,.6f,15),new Vector3(.65f,.65f,.65f))}){var rock=GameObject.CreatePrimitive(PrimitiveType.Sphere);rock.name="ControlledAftershockRock";rock.transform.position=spec.Item1;rock.transform.localScale=spec.Item2;rock.GetComponent<Renderer>().sharedMaterial=rockMat;var rb=rock.AddComponent<Rigidbody>();rb.isKinematic=true;var prop=rock.AddComponent<EarthquakeReactiveProp>();props.Add(prop);}SetArray(controller,"reactiveProps",props.ToArray());foreach(var spec in new[]{(new Vector3(-6,1,9),new Vector3(2,2,5)),(new Vector3(6,1,14),new Vector3(2,2,5))}){var zone=TriggerMarker("Generated_AftershockRiskZone",spec.Item1,spec.Item2);var risk=zone.AddComponent<AftershockRiskZone>();Set(risk,"aftershock",controller);var marker=VisualBlock("RiskZoneMarker",spec.Item1+new Vector3(0,-.98f,0),new Vector3(2,.03f,4.5f),dangerMat,null);var sign=EmergencySignModel("AftershockRiskSign",spec.Item1+new Vector3(0,0,2));Find(sign.transform,"Label").GetComponent<TextMeshPro>().text="RIESGO: CAÍDA DE ROCAS";}}

    private static void AddVolume(Transform parent,string name){var g=new GameObject("GlobalVolume");g.transform.SetParent(parent);var v=g.AddComponent<Volume>();v.isGlobal=true;v.priority=1;v.sharedProfile=AssetDatabase.LoadAssetAtPath<VolumeProfile>($"Assets/Settings/GuardianMisti/{name}.asset");}
    private static void CreateMenuBackdrop(Transform root){for(int i=0;i<7;i++){var rock=GameObject.CreatePrimitive(PrimitiveType.Sphere);rock.name="VolcanicSilhouette";rock.transform.SetParent(root);rock.transform.position=new Vector3((i-3)*3,-2,9+Mathf.Abs(i-3));rock.transform.localScale=new Vector3(5,3+i%2,4);rock.GetComponent<Renderer>().sharedMaterial=rockMat;}var beacon=BeaconModel("MenuBeacon",new Vector3(5,-1,5));beacon.transform.SetParent(root);}
    private static void BuildLevel01Interior(Transform root)
    {
        var facility=new GameObject("Level01FacilityInterior");facility.transform.SetParent(root);
        VisualBlock("RoomFloor",new Vector3(0,-.02f,1.5f),new Vector3(13,.08f,7),floorMat,facility.transform);VisualBlock("CorridorFloor",new Vector3(0,-.02f,12.5f),new Vector3(6,.08f,15),floorMat,facility.transform);CollisionBlock("Collision_ContinuousFloor",new Vector3(0,-.22f,9),new Vector3(13,.4f,23),facility.transform);
        VisualBlock("RoomCeiling",new Vector3(0,4,1.5f),new Vector3(13,.22f,7),wallMat,facility.transform);VisualBlock("CorridorCeiling",new Vector3(0,4,12.5f),new Vector3(6,.22f,15),wallMat,facility.transform);
        FacilityWall("RoomBackWall",new Vector3(0,2,-2),new Vector3(13,4,.3f),facility.transform);FacilityWall("RoomLeftWall",new Vector3(-6.5f,2,1.5f),new Vector3(.3f,4,7),facility.transform);FacilityWall("RoomRightWall",new Vector3(6.5f,2,1.5f),new Vector3(.3f,4,7),facility.transform);FacilityWall("RoomFrontWallLeft",new Vector3(-4,2,5),new Vector3(5,4,.3f),facility.transform);FacilityWall("RoomFrontWallRight",new Vector3(4,2,5),new Vector3(5,4,.3f),facility.transform);FacilityWall("CorridorLeftWall",new Vector3(-3,2,12.5f),new Vector3(.3f,4,15),facility.transform);FacilityWall("CorridorRightWall",new Vector3(3,2,12.5f),new Vector3(.3f,4,15),facility.transform);
        VisualBlock("DoorHeader",new Vector3(0,3.55f,5),new Vector3(3,.9f,.38f),metalMat,facility.transform);var doorway=Imported("Assets/Prefabs/Environment/KenneyDoorFrame.prefab",facility.transform,new Vector3(0,0,4.82f),Vector3.one);doorway.name="KenneyDoorwayDetail";RemoveColliders(doorway);
        var officeDesk=PrefabInstance("Assets/Prefabs/Environment/Desk.prefab",facility.transform,new Vector3(3.9f,0,-.45f),Vector3.one,"KenneyEmergencyDesk");officeDesk.name="KenneyEmergencyDesk";var chair=PrefabInstance("Assets/Prefabs/Environment/Chair.prefab",facility.transform,new Vector3(3.9f,0,.85f),Vector3.one,"KenneyOfficeChair");chair.name="KenneyOfficeChair";var shelf=PrefabInstance("Assets/Prefabs/Environment/Shelf.prefab",facility.transform,new Vector3(-2.35f,0,8.2f),Vector3.one,"KenneySupplyShelf");shelf.name="KenneySupplyShelf";
        var counter=VisualBlock("BackpackEquipmentCounter",new Vector3(-1.75f,.45f,8.15f),new Vector3(1.4f,.9f,.8f),metalMat,facility.transform);CollisionBlock("Collision_EquipmentCounter",counter.transform.position,counter.transform.localScale,facility.transform);var crate=Imported("Assets/StarterAssets/Environment/Prefabs/Box_350x250x200_Prefab.prefab",facility.transform,new Vector3(-2.15f,.35f,10.25f),new Vector3(.4f,.4f,.4f));crate.name="EmergencySupplyCrate";RemoveColliders(crate);BuildFireExtinguisher(facility.transform,new Vector3(2.55f,.72f,8.1f));BuildElectricalPanel(facility.transform,new Vector3(6.28f,1.75f,2.25f));BuildWindowDetail(facility.transform,new Vector3(6.3f,2.35f,-.25f));
        var emergencyPoster=WallInformationPanel("EmergencyPoster",new Vector3(-6.42f,2.15f,1.8f),"DURANTE EL SISMO\nAGÁCHATE · CÚBRETE · SUJÉTATE",dangerMat,facility.transform);emergencyPoster.transform.localRotation=Quaternion.Euler(0,90,0);WallInformationPanel("EvacuationMap",new Vector3(3.6f,2.15f,4.79f),"MAPA DE EVACUACIÓN\nUSTED ESTÁ AQUÍ  →  SALIDA",safeMat,facility.transform);WallInformationPanel("EquipmentAreaSign",new Vector3(-1.6f,2.75f,7.85f),"EQUIPO DE EMERGENCIA",dangerMat,facility.transform);WallInformationPanel("TerminalRouteSign",new Vector3(0,2.75f,10.4f),"→  CONTROL DE EVACUACIÓN",safeMat,facility.transform);WallInformationPanel("ExitDirectionSign",new Vector3(0,2.75f,15.3f),"↑  SALIDA",safeMat,facility.transform);
        var exitFrame=Imported("Assets/Prefabs/Environment/KenneyDoorFrame.prefab",facility.transform,new Vector3(0,0,18.75f),Vector3.one);exitFrame.name="ExitDoorFrame";RemoveColliders(exitFrame);
        for(int i=0;i<4;i++)CeilingFixture(facility.transform,new Vector3(0,3.72f,-.2f+i*5.1f));for(int i=0;i<3;i++)EmergencyLight(facility.transform,new Vector3(i%2==0?-2.7f:2.7f,3.15f,7.2f+i*4.8f));
    }

    private static GameObject InteriorProtectionZoneModel()
    {
        var root=new GameObject("InteriorProtectionZone");
        var desk=new GameObject("Generated_ProtectionDesk");desk.transform.SetParent(root.transform,false);
        var imported=PrefabInstance("Assets/Prefabs/Environment/Desk.prefab",desk.transform,Vector3.zero,Vector3.one,"KenneyProtectionDesk");RemoveColliders(imported);imported.transform.localPosition=new Vector3(0,.12f,.35f);imported.transform.localScale=new Vector3(1.28f,1.12f,1.45f);
        VisualBlock("ReinforcedTop",new Vector3(0,1.25f,.2f),new Vector3(3.15f,.16f,1.85f),metalMat,desk.transform);CollisionBlock("Collision_ProtectionTop",new Vector3(0,1.25f,.2f),new Vector3(3.15f,.16f,1.85f),desk.transform);
        foreach(float x in new[]{-1.42f,1.42f})foreach(float z in new[]{-.62f,.92f}){VisualBlock("StructuralSupport",new Vector3(x,.62f,z),new Vector3(.14f,1.24f,.14f),darkMat,desk.transform);CollisionBlock("Collision_ProtectionSupport",new Vector3(x,.62f,z),new Vector3(.14f,1.24f,.14f),desk.transform);}
        VisualBlock("ReinforcedFrame",new Vector3(0,1.12f,1.02f),new Vector3(3.05f,.13f,.13f),safeMat,desk.transform);
        var floor=VisualBlock("ProtectionFloorBoundary",new Vector3(0,.018f,.15f),new Vector3(2.55f,.025f,1.65f),safeMat,root.transform);
        var trigger=new GameObject("Generated_ProtectionTrigger");trigger.transform.SetParent(root.transform,false);trigger.transform.localPosition=new Vector3(0,.58f,.08f);var box=trigger.AddComponent<BoxCollider>();box.size=new Vector3(2.42f,1.12f,1.45f);box.isTrigger=true;var controller=trigger.AddComponent<EarthquakeProtectionTrigger>();Set(controller,"floorBoundaryRenderer",floor.GetComponent<Renderer>());Set(controller,"objectiveId",GameIds.Level01Protect);Set(controller,"requiredDwellSeconds",2f);
        foreach(float x in new[]{-1.18f,1.18f})VisualBlock("ProtectionSignSupport",new Vector3(x,1.58f,1.05f),new Vector3(.08f,.72f,.08f),darkMat,root.transform);
        var sign=VisualBlock("Generated_ProtectionSign",new Vector3(0,2.02f,1.04f),new Vector3(2.85f,.52f,.08f),darkMat,root.transform);ProtectionLabel(root.transform,"ProtectionZoneTitle",new Vector3(0,2.02f,.99f),"ZONA DE PROTECCIÓN",new Vector2(7f,1.3f),3.2f);
        var instruction=VisualBlock("Generated_ProtectionInstruction",new Vector3(0,1.63f,1.035f),new Vector3(2.45f,.25f,.07f),safeMat,root.transform);ProtectionLabel(root.transform,"ProtectionInstructionText",new Vector3(0,1.63f,.995f),"AGÁCHATE, CÚBRETE Y SUJÉTATE",new Vector2(9f,1.2f),2.1f);
        var icon=VisualBlock("EmergencyProtectionIcon",new Vector3(-1.12f,2.02f,.99f),new Vector3(.34f,.34f,.04f),safeMat,root.transform);VisualBlock("ProtectionIconVertical",new Vector3(-1.12f,2.02f,.965f),new Vector3(.07f,.24f,.025f),emissiveMat,root.transform);VisualBlock("ProtectionIconHorizontal",new Vector3(-1.12f,2.02f,.96f),new Vector3(.24f,.07f,.025f),emissiveMat,root.transform);
        var worldIndicator=GameObject.CreatePrimitive(PrimitiveType.Sphere);worldIndicator.name="ProtectionWorldIndicator";worldIndicator.transform.SetParent(root.transform,false);worldIndicator.transform.localPosition=new Vector3(0,2.42f,.92f);worldIndicator.transform.localScale=Vector3.one*.16f;worldIndicator.GetComponent<Renderer>().sharedMaterial=safeMat;UnityEngine.Object.DestroyImmediate(worldIndicator.GetComponent<Collider>());Set(controller,"objectiveIndicator",worldIndicator);worldIndicator.SetActive(false);
        var status=VisualBlock("ProtectionStatusLight",new Vector3(0,1.55f,-.78f),new Vector3(1.25f,.08f,.08f),safeMat,root.transform);Set(controller,"statusLightRenderer",status.GetComponent<Renderer>());
        var lightObject=new GameObject("ProtectionAccentLight");lightObject.transform.SetParent(root.transform,false);lightObject.transform.localPosition=new Vector3(0,2.6f,.2f);var light=lightObject.AddComponent<Light>();light.type=LightType.Spot;light.range=5f;light.spotAngle=72f;light.color=Cyan;light.intensity=1.3f;light.shadows=LightShadows.None;lightObject.transform.localRotation=Quaternion.Euler(90,0,0);Set(controller,"accentLight",light);
        return root;
    }
    private static void BuildProtectionDesk(Transform parent){var desk=new GameObject("ProtectionDesk");desk.transform.SetParent(parent);VisualBlock("ReinforcedTop",new Vector3(-3.2f,1.15f,1.35f),new Vector3(3,.18f,1.8f),metalMat,desk.transform);CollisionBlock("Collision_DeskTop",new Vector3(-3.2f,1.15f,1.35f),new Vector3(3,.18f,1.8f),desk.transform);foreach(float x in new[]{-4.45f,-1.95f})foreach(float z in new[]{.7f,2f}){VisualBlock("DeskLeg",new Vector3(x,.57f,z),new Vector3(.16f,1.14f,.16f),darkMat,desk.transform);CollisionBlock("Collision_DeskLeg",new Vector3(x,.57f,z),new Vector3(.16f,1.14f,.16f),desk.transform);}VisualBlock("ProtectionEdge",new Vector3(-3.2f,1.25f,.49f),new Vector3(3,.18f,.1f),safeMat,desk.transform);}
    private static void BuildFireExtinguisher(Transform parent,Vector3 position){var root=new GameObject("FireExtinguisher");root.transform.SetParent(parent);root.transform.position=position;var body=GameObject.CreatePrimitive(PrimitiveType.Cylinder);body.name="ExtinguisherBody";body.transform.SetParent(root.transform,false);body.transform.localScale=new Vector3(.22f,.62f,.22f);body.GetComponent<Renderer>().sharedMaterial=dangerMat;var top=GameObject.CreatePrimitive(PrimitiveType.Sphere);top.name="Valve";top.transform.SetParent(root.transform,false);top.transform.localPosition=new Vector3(0,.68f,0);top.transform.localScale=Vector3.one*.28f;top.GetComponent<Renderer>().sharedMaterial=metalMat;UnityEngine.Object.DestroyImmediate(top.GetComponent<Collider>());SignChild(root.transform,"EXTINTOR",new Vector3(0,.15f,-.24f));}
    private static void BuildElectricalPanel(Transform parent,Vector3 p){VisualBlock("ElectricalPanel",p,new Vector3(.12f,1.4f,1.25f),metalMat,parent);for(int i=0;i<3;i++)VisualBlock("BreakerIndicator",p+new Vector3(-.08f,.35f-i*.35f,-.35f),new Vector3(.05f,.14f,.14f),i==0?emissiveMat:accentMat,parent);}
    private static void BuildWindowDetail(Transform parent,Vector3 p){VisualBlock("WindowFrame",p,new Vector3(.12f,1.6f,2.6f),darkMat,parent);VisualBlock("WindowGlass",p+new Vector3(-.07f,0,0),new Vector3(.05f,1.32f,2.3f),accentMat,parent);VisualBlock("WindowMullion",p+new Vector3(-.11f,0,0),new Vector3(.05f,1.45f,.08f),metalMat,parent);}
    private static void ProtectionLabel(Transform parent,string name,Vector3 position,string text,Vector2 rect,float fontSize){var label=new GameObject(name);label.transform.SetParent(parent,false);label.transform.localPosition=position;label.transform.localScale=Vector3.one*.2f;var tmp=label.AddComponent<TextMeshPro>();tmp.text=text;tmp.fontSize=fontSize;tmp.enableAutoSizing=false;tmp.alignment=TextAlignmentOptions.Center;tmp.color=Color.white;tmp.rectTransform.sizeDelta=rect;tmp.enableWordWrapping=false;tmp.overflowMode=TextOverflowModes.Overflow;tmp.raycastTarget=false;}
    private static GameObject WallInformationPanel(string name,Vector3 p,string text,Material material,Transform parent){var panel=VisualBlock(name,p,new Vector3(2.7f,1.05f,.08f),material,parent);FacilityLabel(panel.transform,text);return panel;}
    private static void FacilitySign(string name,string text,Vector3 p,Vector3 size,Material material){var panel=VisualBlock(name,p,size,material,null);FacilityLabel(panel.transform,text);}
    private static void FacilityLabel(Transform parent,string text){var label=new GameObject("FacilityLabel");label.transform.SetParent(parent,false);label.transform.localPosition=new Vector3(0,0,-.56f);float worldScale=.85f*Mathf.Min(parent.localScale.x/9.2f,parent.localScale.y/3.2f);label.transform.localScale=new Vector3(worldScale/parent.localScale.x,worldScale/parent.localScale.y,worldScale/Mathf.Max(.001f,parent.localScale.z));var tmp=label.AddComponent<TextMeshPro>();tmp.text=text;tmp.fontSize=1.4f;tmp.enableAutoSizing=true;tmp.fontSizeMin=.55f;tmp.fontSizeMax=1.4f;tmp.alignment=TextAlignmentOptions.Center;tmp.color=Color.white;tmp.rectTransform.sizeDelta=new Vector2(9.2f,3.2f);tmp.enableWordWrapping=true;tmp.raycastTarget=false;}
    private static void CeilingFixture(Transform parent,Vector3 p){var fixture=VisualBlock("CeilingLightFixture",p,new Vector3(1.8f,.12f,.55f),emissiveMat,parent);var light=fixture.AddComponent<Light>();light.type=LightType.Point;light.range=7;light.intensity=1.35f;light.color=new Color(.86f,.93f,1f);light.shadows=LightShadows.Soft;}
    private static GameObject VisualBlock(string name,Vector3 p,Vector3 scale,Material material,Transform parent){var block=Cube(name,p,scale,material);block.transform.SetParent(parent);UnityEngine.Object.DestroyImmediate(block.GetComponent<Collider>());return block;}
    private static GameObject CollisionBlock(string name,Vector3 p,Vector3 size,Transform parent){var block=new GameObject(name);block.transform.SetParent(parent);block.transform.position=p;block.AddComponent<BoxCollider>().size=size;return block;}
    private static void FacilityWall(string name,Vector3 p,Vector3 size,Transform parent){VisualBlock(name,p,size,wallMat,parent);CollisionBlock("Collision_"+name,p,size,parent);}
    private static void BuildEnvironment(Transform root,bool level2){var ground=Cube("Collision_Ground",new Vector3(0,-.25f,10),new Vector3(18,.5f,28),level2?rockMat:floorMat);ground.transform.SetParent(root);for(int side=-1;side<=1;side+=2){var wall=Cube("StructureWall",new Vector3(side*8.5f,2.2f,10),new Vector3(.45f,4.5f,28),level2?rockMat:wallMat);wall.transform.SetParent(root);}if(level2){for(int i=0;i<16;i++){var r=GameObject.CreatePrimitive(PrimitiveType.Sphere);r.name="VolcanicRock";r.transform.SetParent(root);r.transform.position=new Vector3((i%2==0?-1:1)*(5.5f+(i%3)),.3f,1+i*1.35f);r.transform.localScale=new Vector3(1.2f+i%3,.8f+(i%2),1.5f);r.GetComponent<Renderer>().sharedMaterial=rockMat;}for(int i=0;i<6;i++)RoutePost(root,new Vector3((i%2==0?-1:1)*4,.8f,3+i*3));}else{for(int section=0;section<5;section++){float z=2+section*4;var beam=Cube("FacilityOverheadBeam",new Vector3(0,3.8f,z),new Vector3(16,.22f,.35f),metalMat);beam.transform.SetParent(root);for(int side=-1;side<=1;side+=2){var column=Cube("FacilitySupport",new Vector3(side*7.6f,1.8f,z),new Vector3(.35f,3.6f,.35f),metalMat);column.transform.SetParent(root);}}for(int i=0;i<6;i++){var crate=Imported("Assets/StarterAssets/Environment/Prefabs/Box_350x250x200_Prefab.prefab",root,new Vector3((i%2==0?-1:1)*5,.7f,3+i*2.2f),new Vector3(.45f,.45f,.45f));crate.name="EmergencySupplyCrate";RemoveColliders(crate);}for(int i=0;i<5;i++)EmergencyLight(root,new Vector3(i%2==0?-7.7f:7.7f,3.2f,3+i*4));}DressWithExternalAssets(root,level2);}
    private static void DressWithExternalAssets(Transform root,bool level2){if(level2){for(int i=0;i<6;i++){var rock=PrefabInstance("Assets/Prefabs/Environment/KenneyRock.prefab",root,new Vector3(i%2==0?-6f:6f,.35f,2+i*3),new Vector3(1+i%3*.35f,1,1),"KenneyRockLandmark");}var sign=PrefabInstance("Assets/Prefabs/Environment/EmergencySign.prefab",root,new Vector3(-3,0,15),Vector3.one,"KenneyEvacuationSign");sign.name="KenneyEvacuationSign";var tent=PrefabInstance("Assets/Prefabs/Environment/KenneyRescueTent.prefab",root,new Vector3(5,0,20),Vector3.one,"KenneyRescueTent");tent.name="KenneyRescueTent";}else{var desk=PrefabInstance("Assets/Prefabs/Environment/Desk.prefab",root,new Vector3(-5,0,1.2f),Vector3.one,"KenneyEmergencyDesk");desk.name="KenneyEmergencyDesk";var chair=PrefabInstance("Assets/Prefabs/Environment/Chair.prefab",root,new Vector3(-4.5f,0,2.4f),Vector3.one,"KenneyOfficeChair");chair.name="KenneyOfficeChair";var shelf=PrefabInstance("Assets/Prefabs/Environment/Shelf.prefab",root,new Vector3(6.5f,0,6),Vector3.one,"KenneySupplyShelf");shelf.name="KenneySupplyShelf";var doorway=Imported("Assets/Prefabs/Environment/KenneyDoorFrame.prefab",root,new Vector3(6.4f,0,3.5f),Vector3.one);doorway.name="KenneyDoorwayDetail";}}
    private static GameObject ExternalWrapper(string name,string path,Vector3 scale,Material material,Vector3 colliderSize){var source=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(source==null)throw new Exception("Missing verified external model: "+path);var root=new GameObject(name);var visual=(GameObject)PrefabUtility.InstantiatePrefab(source);visual.name="Visual_"+name;visual.transform.SetParent(root.transform,false);visual.transform.localScale=scale;RemoveColliders(visual);foreach(var renderer in visual.GetComponentsInChildren<Renderer>())renderer.sharedMaterial=material;var collider=root.AddComponent<BoxCollider>();collider.size=colliderSize;return root;}
    private static GameObject Imported(string path,Transform parent,Vector3 pos,Vector3 scale){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(prefab==null)throw new Exception("Required imported asset unavailable: "+path);var g=(GameObject)PrefabUtility.InstantiatePrefab(prefab);PrefabUtility.UnpackPrefabInstance(g,PrefabUnpackMode.Completely,InteractionMode.AutomatedAction);g.transform.SetParent(parent);g.transform.position=pos;g.transform.localScale=scale;foreach(var r in g.GetComponentsInChildren<Renderer>()){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++)if(mats[i]==null)mats[i]=wallMat;r.sharedMaterials=mats;}return g;}
    private static GameObject PrefabInstance(string path,Transform parent,Vector3 pos,Vector3 scale,string instanceName){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(prefab==null)throw new Exception("Required project prefab unavailable: "+path);var g=(GameObject)PrefabUtility.InstantiatePrefab(prefab);g.transform.SetParent(parent);g.transform.position=pos;g.transform.localScale=scale;g.name=instanceName;return g;}
    private static void RemoveColliders(GameObject root){foreach(var c in root.GetComponentsInChildren<Collider>())UnityEngine.Object.DestroyImmediate(c);}
    private static void EmergencyLight(Transform root,Vector3 pos){var g=new GameObject("EmergencyLight");g.transform.SetParent(root);g.transform.position=pos;var l=g.AddComponent<Light>();l.type=LightType.Point;l.range=6;l.intensity=2;l.color=new Color(1,.18f,.05f);l.shadows=LightShadows.None;var lens=GameObject.CreatePrimitive(PrimitiveType.Sphere);lens.name="Lens";lens.transform.SetParent(g.transform);lens.transform.localScale=Vector3.one*.22f;lens.GetComponent<Renderer>().sharedMaterial=emissiveMat;UnityEngine.Object.DestroyImmediate(lens.GetComponent<Collider>());}
    private static void RoutePost(Transform root,Vector3 pos){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name="EvacuationRoutePost";g.transform.SetParent(root);g.transform.position=pos;g.transform.localScale=new Vector3(.12f,.8f,.12f);g.GetComponent<Renderer>().sharedMaterial=metalMat;var cap=GameObject.CreatePrimitive(PrimitiveType.Sphere);cap.transform.SetParent(g.transform);cap.transform.localPosition=new Vector3(0,1,0);cap.transform.localScale=new Vector3(2, .3f,2);cap.GetComponent<Renderer>().sharedMaterial=safeMat;UnityEngine.Object.DestroyImmediate(cap.GetComponent<Collider>());}
    private static GameObject ComposedDoor(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;var blocker=root.AddComponent<BoxCollider>();blocker.center=new Vector3(0,0,0);blocker.size=new Vector3(2.35f,2.85f,.16f);var frame=new GameObject("DoorFrame");frame.transform.SetParent(root.transform,false);foreach(var spec in new[]{(new Vector3(-1.38f,0,0),new Vector3(.25f,3.25f,.4f)),(new Vector3(1.38f,0,0),new Vector3(.25f,3.25f,.4f)),(new Vector3(0,1.75f,0),new Vector3(3,.25f,.4f))}){var part=Cube("StructuralFrame",spec.Item1,spec.Item2,darkMat);part.transform.SetParent(frame.transform,false);}var leaf=new GameObject("DoorLeaf");leaf.transform.SetParent(root.transform,false);leaf.transform.localPosition=new Vector3(-1.18f,0,0);var panel=Cube("DoorPanel",new Vector3(1.18f,0,0),new Vector3(2.36f,2.85f,.16f),metalMat);panel.transform.SetParent(leaf.transform,false);foreach(float y in new[]{-.8f,.8f}){var brace=Cube("DoorBrace",new Vector3(1.18f,y,-.13f),new Vector3(2.1f,.12f,.1f),accentMat);brace.transform.SetParent(leaf.transform,false);}var bar=Cube("EmergencyPushBar",new Vector3(1.18f,0,-.22f),new Vector3(1.65f,.12f,.12f),dangerMat);bar.transform.SetParent(leaf.transform,false);foreach(float y in new[]{-.9f,.9f}){var hinge=GameObject.CreatePrimitive(PrimitiveType.Cylinder);hinge.name="Hinge";hinge.transform.SetParent(leaf.transform,false);hinge.transform.localPosition=new Vector3(0,y,0);hinge.transform.localScale=new Vector3(.06f,.16f,.06f);hinge.GetComponent<Renderer>().sharedMaterial=darkMat;UnityEngine.Object.DestroyImmediate(hinge.GetComponent<Collider>());}var sign=VisualBlock("MountedExitSign",new Vector3(0,2.08f,-.04f),new Vector3(1.45f,.4f,.1f),safeMat,root.transform);ProtectionLabel(root.transform,"MountedExitLabel",new Vector3(0,2.08f,-.32f),"SALIDA",new Vector2(5f,1.2f),3.2f);return root;}
    private static GameObject BackpackModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;root.AddComponent<BoxCollider>().size=new Vector3(.8f,1,.5f);var bag=Cube("CanvasBag",Vector3.zero,new Vector3(.72f,.9f,.42f),dangerMat);bag.transform.SetParent(root.transform,false);var pocket=Cube("FrontPocket",new Vector3(0,-.14f,-.28f),new Vector3(.55f,.38f,.16f),accentMat);pocket.transform.SetParent(root.transform,false);for(int side=-1;side<=1;side+=2){var sidePocket=Cube("SidePocket",new Vector3(side*.43f,-.18f,0),new Vector3(.16f,.42f,.3f),darkMat);sidePocket.transform.SetParent(root.transform,false);}var handle=GameObject.CreatePrimitive(PrimitiveType.Cylinder);handle.name="CarryHandle";handle.transform.SetParent(root.transform,false);handle.transform.localPosition=new Vector3(0,.55f,0);handle.transform.localRotation=Quaternion.Euler(0,0,90);handle.transform.localScale=new Vector3(.04f,.22f,.04f);handle.GetComponent<Renderer>().sharedMaterial=darkMat;UnityEngine.Object.DestroyImmediate(handle.GetComponent<Collider>());for(int i=-1;i<=1;i+=2){var strap=Cube("Strap",new Vector3(i*.22f,0,-.24f),new Vector3(.1f,.82f,.06f),darkMat);strap.transform.SetParent(root.transform,false);}SignChild(root.transform,"EMERGENCIA",new Vector3(0,.05f,-.26f));return root;}
    private static GameObject RadioModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;root.AddComponent<BoxCollider>().size=new Vector3(.65f,.8f,.35f);var body=Cube("RadioBody",Vector3.zero,new Vector3(.6f,.72f,.3f),darkMat);body.transform.SetParent(root.transform,false);var screen=Cube("RadioScreen",new Vector3(0,.12f,-.18f),new Vector3(.38f,.2f,.04f),accentMat);screen.transform.SetParent(root.transform,false);for(int i=0;i<4;i++){var grille=Cube("SpeakerGrille",new Vector3(-.15f+i*.1f,-.18f,-.18f),new Vector3(.035f,.22f,.025f),metalMat);grille.transform.SetParent(root.transform,false);}var button=GameObject.CreatePrimitive(PrimitiveType.Cylinder);button.name="EmergencyButton";button.transform.SetParent(root.transform,false);button.transform.localPosition=new Vector3(.2f,.32f,-.2f);button.transform.localRotation=Quaternion.Euler(90,0,0);button.transform.localScale=new Vector3(.06f,.025f,.06f);button.GetComponent<Renderer>().sharedMaterial=emissiveMat;UnityEngine.Object.DestroyImmediate(button.GetComponent<Collider>());SignChild(root.transform,"SOS",new Vector3(0,.36f,-.2f));var antenna=GameObject.CreatePrimitive(PrimitiveType.Cylinder);antenna.transform.SetParent(root.transform,false);antenna.transform.localPosition=new Vector3(.2f,.7f,0);antenna.transform.localScale=new Vector3(.035f,.45f,.035f);antenna.GetComponent<Renderer>().sharedMaterial=metalMat;UnityEngine.Object.DestroyImmediate(antenna.GetComponent<Collider>());return root;}
    private static GameObject KeyModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;root.AddComponent<BoxCollider>().size=new Vector3(.7f,.25f,.9f);var card=Cube("AccessCard",Vector3.zero,new Vector3(.65f,.12f,.85f),accentMat);card.transform.SetParent(root.transform,false);var stripe=Cube("AccessStripe",new Vector3(0,.08f,.18f),new Vector3(.5f,.03f,.12f),emissiveMat);stripe.transform.SetParent(root.transform,false);var chip=Cube("SecurityChip",new Vector3(-.18f,.085f,-.12f),new Vector3(.17f,.035f,.18f),metalMat);chip.transform.SetParent(root.transform,false);var eyelet=GameObject.CreatePrimitive(PrimitiveType.Cylinder);eyelet.name="BadgeEyelet";eyelet.transform.SetParent(root.transform,false);eyelet.transform.localPosition=new Vector3(0,.1f,.34f);eyelet.transform.localScale=new Vector3(.08f,.025f,.08f);eyelet.GetComponent<Renderer>().sharedMaterial=darkMat;UnityEngine.Object.DestroyImmediate(eyelet.GetComponent<Collider>());SignChild(root.transform,"ACCESO",new Vector3(.08f,.09f,-.27f));var highlight=GameObject.CreatePrimitive(PrimitiveType.Cylinder);highlight.name="PickupHighlight";highlight.transform.SetParent(root.transform,false);highlight.transform.localPosition=new Vector3(0,-.1f,0);highlight.transform.localScale=new Vector3(.48f,.015f,.48f);highlight.GetComponent<Renderer>().sharedMaterial=emissiveMat;UnityEngine.Object.DestroyImmediate(highlight.GetComponent<Collider>());return root;}
    private static GameObject TerminalModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;root.AddComponent<BoxCollider>().center=new Vector3(0,1,0);root.GetComponent<BoxCollider>().size=new Vector3(1.1f,2,.8f);var stand=Cube("TerminalHousing",new Vector3(0,.8f,0),new Vector3(1,1.6f,.7f),metalMat);stand.transform.SetParent(root.transform,false);var screen=Cube("StatusLight",new Vector3(0,1.25f,-.38f),new Vector3(.72f,.55f,.05f),accentMat);screen.transform.SetParent(root.transform,false);var button=GameObject.CreatePrimitive(PrimitiveType.Cylinder);button.name="ActivationButton";button.transform.SetParent(root.transform,false);button.transform.localPosition=new Vector3(0,.72f,-.43f);button.transform.localRotation=Quaternion.Euler(90,0,0);button.transform.localScale=new Vector3(.12f,.035f,.12f);button.GetComponent<Renderer>().sharedMaterial=dangerMat;UnityEngine.Object.DestroyImmediate(button.GetComponent<Collider>());for(int i=-1;i<=1;i++){var lamp=GameObject.CreatePrimitive(PrimitiveType.Sphere);lamp.name="IndicatorLight";lamp.transform.SetParent(root.transform,false);lamp.transform.localPosition=new Vector3(i*.22f,.44f,-.4f);lamp.transform.localScale=Vector3.one*.07f;lamp.GetComponent<Renderer>().sharedMaterial=i==0?emissiveMat:safeMat;UnityEngine.Object.DestroyImmediate(lamp.GetComponent<Collider>());}SignChild(root.transform,"EVACUACIÓN",new Vector3(0,.22f,-.39f));return root;}
    private static GameObject BeaconModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;root.AddComponent<CapsuleCollider>().center=new Vector3(0,1.5f,0);root.GetComponent<CapsuleCollider>().height=3;root.GetComponent<CapsuleCollider>().radius=.65f;var basePlate=GameObject.CreatePrimitive(PrimitiveType.Cylinder);basePlate.name="StructuralBase";basePlate.transform.SetParent(root.transform,false);basePlate.transform.localPosition=new Vector3(0,.12f,0);basePlate.transform.localScale=new Vector3(.9f,.12f,.9f);basePlate.GetComponent<Renderer>().sharedMaterial=darkMat;UnityEngine.Object.DestroyImmediate(basePlate.GetComponent<Collider>());var mast=GameObject.CreatePrimitive(PrimitiveType.Cylinder);mast.name="BeaconMast";mast.transform.SetParent(root.transform,false);mast.transform.localPosition=new Vector3(0,1.4f,0);mast.transform.localScale=new Vector3(.35f,1.4f,.35f);mast.GetComponent<Renderer>().sharedMaterial=metalMat;UnityEngine.Object.DestroyImmediate(mast.GetComponent<Collider>());var panel=Cube("ControlPanel",new Vector3(0,1.05f,-.42f),new Vector3(.72f,.62f,.18f),darkMat);panel.transform.SetParent(root.transform,false);var panelScreen=Cube("ControlScreen",new Vector3(0,1.17f,-.53f),new Vector3(.48f,.2f,.03f),accentMat);panelScreen.transform.SetParent(root.transform,false);var panelButton=GameObject.CreatePrimitive(PrimitiveType.Cylinder);panelButton.name="ControlButton";panelButton.transform.SetParent(root.transform,false);panelButton.transform.localPosition=new Vector3(0,.9f,-.54f);panelButton.transform.localRotation=Quaternion.Euler(90,0,0);panelButton.transform.localScale=new Vector3(.08f,.025f,.08f);panelButton.GetComponent<Renderer>().sharedMaterial=dangerMat;UnityEngine.Object.DestroyImmediate(panelButton.GetComponent<Collider>());var light=GameObject.CreatePrimitive(PrimitiveType.Sphere);light.name="StatusLight";light.transform.SetParent(root.transform,false);light.transform.localPosition=new Vector3(0,2.9f,0);light.transform.localScale=Vector3.one*.75f;light.GetComponent<Renderer>().sharedMaterial=emissiveMat;UnityEngine.Object.DestroyImmediate(light.GetComponent<Collider>());var glow=light.AddComponent<Light>();glow.type=LightType.Point;glow.range=12;glow.intensity=2.5f;glow.color=new Color(.1f,.75f,1f);glow.shadows=LightShadows.None;for(int i=0;i<3;i++){var leg=Cube("Support",new Vector3((i-1)*.55f,.35f,0),new Vector3(.16f,.7f,.16f),darkMat);leg.transform.SetParent(root.transform,false);}return root;}
    private static GameObject TriggerMarker(string name,Vector3 pos,Vector3 size){var g=new GameObject(name);g.transform.position=pos;var c=g.AddComponent<BoxCollider>();c.size=size;c.isTrigger=true;return g;}
    private static void SafeZoneVisual(Transform root,Vector3 local){var pad=GameObject.CreatePrimitive(PrimitiveType.Cylinder);pad.name="RescuePlatform";pad.transform.SetParent(root,false);pad.transform.localPosition=local;pad.transform.localScale=new Vector3(3.2f,.12f,3.2f);pad.GetComponent<Renderer>().sharedMaterial=safeMat;UnityEngine.Object.DestroyImmediate(pad.GetComponent<Collider>());var crossA=Cube("RescueSymbol",local+new Vector3(0,.13f,0),new Vector3(2.2f,.025f,.55f),emissiveMat);crossA.transform.SetParent(root,false);var crossB=Cube("RescueSymbol",local+new Vector3(0,.13f,0),new Vector3(.55f,.025f,2.2f),emissiveMat);crossB.transform.SetParent(root,false);for(int i=0;i<8;i++){float a=i*Mathf.PI/4;RoutePost(root,new Vector3(Mathf.Cos(a)*2.7f,0,Mathf.Sin(a)*2.7f)+root.position);}var sign=EmergencySignModel("SafeZoneSign",root.position+new Vector3(0,0,2.6f));sign.transform.SetParent(root);SignChild(sign.transform,"ZONA SEGURA",new Vector3(0,1.55f,-.08f));}
    private static GameObject EmergencySignModel(string name,Vector3 pos){var root=new GameObject(name);root.transform.position=pos;var panel=Cube("SignPanel",new Vector3(0,1.55f,0),new Vector3(2.4f,.72f,.12f),safeMat);panel.transform.SetParent(root.transform,false);for(int side=-1;side<=1;side+=2){var post=Cube("SignPost",new Vector3(side*.85f,.72f,.06f),new Vector3(.12f,1.45f,.12f),metalMat);post.transform.SetParent(root.transform,false);}SignChild(root.transform,"EMERGENCIA",new Vector3(0,1.55f,-.08f));return root;}
    private static GameObject Sign(string text,Vector3 pos,Material mat){var g=Cube("Sign_"+text,pos,new Vector3(4,.8f,.12f),mat);SignChild(g.transform,text,new Vector3(0,0,-.56f));return g;}
    private static void SignChild(Transform parent,string text,Vector3 local){var g=new GameObject("Label");g.transform.SetParent(parent,false);g.transform.localPosition=local;g.transform.localRotation=Quaternion.identity;var t=g.AddComponent<TextMeshPro>();t.text=text;t.fontSize=2;t.alignment=TextAlignmentOptions.Center;t.color=Color.white;}
    private static EarthquakeReactiveProp[] BuildEarthquakeProps(){var specs=new[]{("ReactiveChair",new Vector3(5,.45f,3.25f),new Vector3(.65f,.9f,.65f)),("ReactiveSupplyBox",new Vector3(-5,.35f,-.85f),new Vector3(.75f,.7f,.75f)),("ReactiveShelfObject",new Vector3(5.15f,.3f,1.55f),new Vector3(.45f,.6f,.45f)),("ReactiveHangingLamp",new Vector3(5.2f,3.1f,-.7f),new Vector3(.55f,.35f,.55f)),("ReactiveEmergencyCanister",new Vector3(-5.3f,.45f,3.55f),new Vector3(.42f,.9f,.42f))};var list=new List<EarthquakeReactiveProp>();foreach(var spec in specs){var go=Cube(spec.Item1,spec.Item2,spec.Item3,spec.Item1.Contains("Emergency")?dangerMat:metalMat);var body=go.AddComponent<Rigidbody>();body.mass=.8f;body.isKinematic=true;body.useGravity=true;body.maxLinearVelocity=2.2f;body.maxAngularVelocity=6f;var detail=Cube("ReactiveDetail",spec.Item2+new Vector3(0,spec.Item3.y*.55f,0),new Vector3(spec.Item3.x*.65f,.08f,spec.Item3.z*.65f),accentMat);detail.transform.SetParent(go.transform);UnityEngine.Object.DestroyImmediate(detail.GetComponent<Collider>());list.Add(go.AddComponent<EarthquakeReactiveProp>());}return list.ToArray();}
    private static AudioSource EarthquakeAudio(GameObject parent,string name,bool loop){var source=parent.AddComponent<AudioSource>();source.playOnAwake=false;source.loop=loop;source.spatialBlend=0;source.volume=0;return source;}
    private static ParticleSystem EarthquakeDebris(Vector3 pos){var ps=Dust(pos,new Vector3(9,.25f,6),18);ps.name="CeilingDebris";var main=ps.main;main.startLifetime=new ParticleSystem.MinMaxCurve(1.2f,2.4f);main.startSpeed=new ParticleSystem.MinMaxCurve(.1f,.45f);main.gravityModifier=.18f;main.startSize=new ParticleSystem.MinMaxCurve(.02f,.06f);main.maxParticles=28;var emission=ps.emission;emission.rateOverTime=0;return ps;}
    private static ParticleSystem Dust(Vector3 pos,Vector3 box,int count){var g=new GameObject("AtmosphericDust");g.transform.position=pos;var ps=g.AddComponent<ParticleSystem>();var main=ps.main;main.maxParticles=Mathf.Min(count,60);main.startLifetime=6;main.startSpeed=.08f;main.startSize=new ParticleSystem.MinMaxCurve(.025f,.065f);main.startColor=new Color(.7f,.62f,.5f,.16f);main.simulationSpace=ParticleSystemSimulationSpace.World;var emission=ps.emission;emission.rateOverTime=Mathf.Min(count/8f,7f);var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Box;shape.scale=box;shape.position=new Vector3(0,.5f,2f);var renderer=g.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterial=vfxMat;renderer.maxParticleSize=.025f;return ps;}
    private static void AddSettings(GameObject panel,FirstPersonController fpc){Text("SensitivityLabel",panel.transform,"SENSIBILIDAD",15,new Vector2(.24f,.31f),new Vector2(250,28),Color.white,FontStyles.Bold);var sens=SliderObj("SensitivitySlider",panel.transform,new Vector2(.53f,.31f),.25f,3f,1f);var sv=Text("SensitivityValue",panel.transform,"1.00",16,new Vector2(.82f,.31f),new Vector2(90,30),Cyan,FontStyles.Bold);Text("VolumeLabel",panel.transform,"VOLUMEN GENERAL",15,new Vector2(.24f,.18f),new Vector2(250,28),Color.white,FontStyles.Bold);var vol=SliderObj("VolumeSlider",panel.transform,new Vector2(.53f,.18f),0,1,1);var vv=Text("VolumeValue",panel.transform,"100%",16,new Vector2(.82f,.18f),new Vector2(90,30),Cyan,FontStyles.Bold);var toggleRoot=ImageObj("ResearchToggle",panel.transform,new Vector2(.19f,.075f),new Vector2(30,30),new Color(.055f,.1f,.13f,1));var check=ImageObj("Checkmark",toggleRoot.transform,new Vector2(.5f,.5f),new Vector2(18,18),Cyan).GetComponent<Image>();var toggle=toggleRoot.AddComponent<Toggle>();toggle.targetGraphic=toggleRoot.GetComponent<Image>();toggle.graphic=check;toggle.isOn=PlayerPrefs.GetInt(SimulationSession.ResearchEnabledKey,0)==1;Text("ResearchLabel",panel.transform,"GUARDAR DATOS ANÓNIMOS DEL SIMULACRO",12,new Vector2(.5f,.09f),new Vector2(520,24),Color.white,FontStyles.Bold);var explanation=Text("ResearchExplanation",panel.transform,"No se sube información; los archivos permanecen en este dispositivo.",10,new Vector2(.5f,.035f),new Vector2(590,24),new Color(.65f,.75f,.78f));var settings=panel.AddComponent<GameplaySettingsController>();Set(settings,"controller",fpc);Set(settings,"sensitivitySlider",sens);Set(settings,"volumeSlider",vol);Set(settings,"sensitivityValue",sv);Set(settings,"volumeValue",vv);Set(settings,"researchToggle",toggle);Set(settings,"researchExplanation",explanation);}
    private static Slider SliderObj(string name,Transform parent,Vector2 anchor,float min,float max,float value){var root=ImageObj(name,parent,anchor,new Vector2(360,28),new Color(.055f,.1f,.13f,1));var fillArea=Rect("Fill Area",root.transform,new Vector2(0,0),new Vector2(1,1));var fr=(RectTransform)fillArea.transform;fr.offsetMin=new Vector2(14,8);fr.offsetMax=new Vector2(-14,-8);var fill=ImageObj("Fill",fillArea.transform,new Vector2(.5f,.5f),new Vector2(332,12),Cyan);fill.GetComponent<Image>().raycastTarget=false;var handleArea=Rect("Handle Slide Area",root.transform,new Vector2(0,0),new Vector2(1,1));var hr=(RectTransform)handleArea.transform;hr.offsetMin=new Vector2(14,0);hr.offsetMax=new Vector2(-14,0);var handle=ImageObj("Handle",handleArea.transform,new Vector2(.5f,.5f),new Vector2(26,26),Color.white);var outline=handle.AddComponent<Outline>();outline.effectColor=Cyan;outline.effectDistance=new Vector2(2,-2);var slider=root.AddComponent<Slider>();slider.fillRect=(RectTransform)fill.transform;slider.handleRect=(RectTransform)handle.transform;slider.targetGraphic=handle.GetComponent<Image>();slider.direction=Slider.Direction.LeftToRight;slider.minValue=min;slider.maxValue=max;slider.value=value;return slider;}

    private static void SetObjectives(ObjectivesManager manager,bool l2)
    {
        var list=l2?new[]{new Objective(GameIds.Level02CollectRadio,"Encuentra la radio de emergencia."),new Objective(GameIds.Level02CollectAccessKey,"Encuentra la llave de acceso."),new Objective(GameIds.Level02ActivateBeacon,"Activa la baliza de emergencia."),new Objective(GameIds.Level02ReachSafeZone,"Llega a la zona segura.")}:new[]{new Objective(GameIds.Level01Preparation,"Prepárate para el inicio del simulacro."),new Objective(GameIds.Level01Protect,"Protégete durante el sismo."),new Objective(GameIds.Level01ExitRoom,"Sal de la habitación."),new Objective(GameIds.Level01CollectBackpack,"Encuentra la mochila de emergencia."),new Objective(GameIds.Level01ActivateEvacuation,"Activa la salida de evacuación."),new Objective(GameIds.Level01ReachExit,"Dirígete al punto de salida.")};
        var so=new SerializedObject(manager);var p=so.FindProperty("objectives");p.arraySize=list.Length;for(int i=0;i<list.Length;i++){var e=p.GetArrayElementAtIndex(i);e.FindPropertyRelative("id").stringValue=list[i].Id;e.FindPropertyRelative("description").stringValue=list[i].Description;}so.ApplyModifiedPropertiesWithoutUndo();
    }
    private static InventorySlotView InventorySlot(Transform parent,string objectName,string id,string label,string spritePath,float x){var slot=Panel(objectName,parent,new Vector2(x,.47f),new Vector2(145,72));slot.GetComponent<Image>().raycastTarget=false;var accent=slot.GetComponent<Image>();var icon=ImageObj("Icon",slot.transform,new Vector2(.24f,.56f),new Vector2(40,40),new Color(.32f,.38f,.42f,.65f)).GetComponent<Image>();icon.raycastTarget=false;icon.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(spritePath);icon.preserveAspect=true;var name=Text("ItemName",slot.transform,label,11,new Vector2(.63f,.42f),new Vector2(84,34),new Color(.65f,.7f,.73f,1),FontStyles.Bold);name.raycastTarget=false;var check=Text("CheckMark",slot.transform,"✓",20,new Vector2(.88f,.78f),new Vector2(28,28),new Color(.15f,1f,.7f),FontStyles.Bold).gameObject;var view=slot.AddComponent<InventorySlotView>();Set(view,"itemId",id);Set(view,"icon",icon);Set(view,"itemName",name);Set(view,"checkMark",check);Set(view,"accent",accent);view.SetObtained(false);return view;}
    private static TMP_Text ResultMetric(Transform parent,string name,string label,float x,float y,float valueSize){var card=Panel(name+"Card",parent,new Vector2(x,y),new Vector2(280,120));card.GetComponent<Image>().color=new Color(.04f,.11f,.14f,.96f);Text(name+"Label",card.transform,label,13,new Vector2(.5f,.72f),new Vector2(250,26),Cyan,FontStyles.Bold);return Text(name+"Value",card.transform,"--",valueSize,new Vector2(.5f,.34f),new Vector2(250,52),Color.white,FontStyles.Bold);}
    private static TMP_Text ResultRow(Transform parent,string name,string label,float x,float y){var row=Panel(name+"Row",parent,new Vector2(x,y),new Vector2(440,54));row.GetComponent<Image>().color=new Color(.035f,.09f,.12f,.94f);var l=Text(name+"Label",row.transform,label,13,new Vector2(.34f,.5f),new Vector2(280,34),new Color(.75f,.82f,.85f));l.alignment=TextAlignmentOptions.MidlineLeft;var v=Text(name+"Value",row.transform,"--",17,new Vector2(.8f,.5f),new Vector2(125,34),Color.white,FontStyles.Bold);v.alignment=TextAlignmentOptions.MidlineRight;return v;}
    private static Button ButtonAt(string name,Transform parent,string label,Vector2 anchor,UnityEngine.Events.UnityAction action){var b=ButtonObj(name,parent,label,anchor,action);((RectTransform)b.transform).sizeDelta=new Vector2(360,64);return b;}
    private static void SetArray(UnityEngine.Object target,string property,Component[] values){var so=new SerializedObject(target);var p=so.FindProperty(property);p.arraySize=values.Length;for(int i=0;i<values.Length;i++)p.GetArrayElementAtIndex(i).objectReferenceValue=values[i];so.ApplyModifiedPropertiesWithoutUndo();}
    private static void WirePauseButtons(GameObject p,PauseController c){Wire(p,"ResumeButton",c.Resume);Wire(p,"RestartButton",c.Reload);Wire(p,"MenuButton",c.MainMenu);}
    private static void WireCompletionButtons(GameObject p,GameCompletionController c){Wire(p,"RestartButton",c.RestartCurrentLevel);Wire(p,"MenuButton",c.ReturnToMainMenu);Wire(p,"ExitButton",c.QuitGame);}
    private static void Wire(GameObject root,string name,UnityEngine.Events.UnityAction action){var b=Find(root.transform,name).GetComponent<Button>();b.onClick.RemoveAllListeners();UnityEventTools.AddPersistentListener(b.onClick,action);}

    private static void PrepareScene(string path){if(File.Exists(path))EditorSceneManager.OpenScene(path,OpenSceneMode.Single);else EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);foreach(var root in SceneManager.GetActiveScene().GetRootGameObjects()){if(root.name=="Generated_GuardianMisti"||root.name=="SimulationSession"||IsLegacyGeneratedRoot(root.name))UnityEngine.Object.DestroyImmediate(root);}}
    private static bool IsLegacyGeneratedRoot(string n)=>new[]{"Main Camera","EventSystem","App","Canvas","GameplayHUD","GameplayPlayer","GameplaySystems","GameplayCursorController","Directional Light","Ground","LeftWall","RightWall","InitialDoor","EmergencyBackpack","EvacuationTerminal","LevelExit","EmergencyRadio","AccessKey","EmergencyBeacon","SafeZone","EVACUACIÓN","ZONA SEGURA"}.Contains(n);
    private static void ConsolidateGenerated(GameObject generated){foreach(var root in SceneManager.GetActiveScene().GetRootGameObjects())if(root!=generated&&root.GetComponent<SimulationSession>()==null)root.transform.SetParent(generated.transform,true);}
    private static void SaveScene(string path){EditorSceneManager.SaveScene(SceneManager.GetActiveScene(),path);}
    private static void EventSystem(){var e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<InputSystemUIInputModule>();}
    private static Canvas CanvasRoot(string name){var g=new GameObject(name);var c=g.AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;var s=g.AddComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1920,1080);g.AddComponent<GraphicRaycaster>();return c;}
    private static GameObject Rect(string name,Transform parent,Vector2 min,Vector2 max){var g=new GameObject(name,typeof(RectTransform));g.transform.SetParent(parent,false);var r=(RectTransform)g.transform;r.anchorMin=min;r.anchorMax=max;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;return g;}
    private static GameObject Panel(string name,Transform parent,Vector2 anchor,Vector2 size){var g=ImageObj(name,parent,anchor,size,new Color(.02f,.06f,.1f,.88f));var o=g.AddComponent<Outline>();o.effectColor=new Color(.12f,.55f,.65f,.35f);o.effectDistance=new Vector2(1,-1);return g;}
    private static GameObject FullPanel(string name,Transform parent,string title){var g=ImageObj(name,parent,new Vector2(.5f,.5f),new Vector2(1920,1080),new Color(0.01f,.025f,.05f,.94f));Text("Title",g.transform,title,48,new Vector2(.5f,.76f),new Vector2(1000,90),Color.white,FontStyles.Bold);return g;}
    private static GameObject ImageObj(string name,Transform parent,Vector2 anchor,Vector2 size,Color color){var g=new GameObject(name,typeof(RectTransform),typeof(CanvasRenderer),typeof(Image));g.transform.SetParent(parent,false);var r=(RectTransform)g.transform;r.anchorMin=r.anchorMax=anchor;r.sizeDelta=size;r.anchoredPosition=Vector2.zero;g.GetComponent<Image>().color=color;return g;}
    private static TextMeshProUGUI Text(string name,Transform parent,string value,float size,Vector2 anchor,Vector2 dims,Color color,FontStyles style=FontStyles.Normal){var g=new GameObject(name,typeof(RectTransform),typeof(CanvasRenderer),typeof(TextMeshProUGUI));g.transform.SetParent(parent,false);var r=(RectTransform)g.transform;r.anchorMin=r.anchorMax=anchor;r.sizeDelta=dims;r.anchoredPosition=Vector2.zero;var t=g.GetComponent<TextMeshProUGUI>();t.text=value;t.fontSize=size;t.color=color;t.alignment=TextAlignmentOptions.Center;t.fontStyle=style;return t;}
    private static Button ButtonObj(string name,Transform parent,string label,Vector2 anchor,UnityEngine.Events.UnityAction action){var g=ImageObj(name,parent,anchor,new Vector2(420,68),new Color(.04f,.34f,.44f,.96f));var b=g.AddComponent<Button>();var colors=b.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1.12f,1.12f,1.12f,1);colors.pressedColor=new Color(.72f,.9f,.94f,1);colors.selectedColor=colors.highlightedColor;colors.disabledColor=new Color(.45f,.45f,.45f,.5f);b.colors=colors;var t=Text("Label",g.transform,label,20,new Vector2(.5f,.5f),new Vector2(400,60),Color.white,FontStyles.Bold);t.raycastTarget=false;if(action!=null)UnityEventTools.AddPersistentListener(b.onClick,action);return b;}
    private static GameObject Cube(string name,Vector3 pos,Vector3 scale,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.position=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=mat;return g;}
    private static void TextWorld(string text,Vector3 pos,Color color){var g=new GameObject(text);g.transform.position=pos;g.transform.rotation=Quaternion.Euler(0,180,0);var t=g.AddComponent<TextMeshPro>();t.text=text;t.fontSize=3;t.alignment=TextAlignmentOptions.Center;t.color=color;}
    private static Transform Find(Transform root,string name){foreach(Transform t in root.GetComponentsInChildren<Transform>(true))if(t.name==name)return t;throw new Exception($"Missing child {name}");}
    private static void Set(UnityEngine.Object target,string property,object value){var so=new SerializedObject(target);var p=so.FindProperty(property);if(p==null)throw new Exception($"{target.GetType().Name}.{property} not serialized");switch(value){case UnityEngine.Object o:p.objectReferenceValue=o;break;case string s:p.stringValue=s;break;case bool b:p.boolValue=b;break;case float f:p.floatValue=f;break;case Behaviour[] a:p.arraySize=a.Length;for(int i=0;i<a.Length;i++)p.GetArrayElementAtIndex(i).objectReferenceValue=a[i];break;default:throw new Exception($"Unsupported serialized value {value?.GetType()}");}so.ApplyModifiedPropertiesWithoutUndo();}
}
